export const aaNumberThreeContent = {
  paragraphs: [
    { pageNum: "180" },
    { text: `My name is Fitz M. In A.A. I am Number Three, for I was the third man to be brought into A.A.` },
    { text: `I was born July 21, 1896, in New Castle, Indiana. My family moved to Indianapolis when I was six weeks old. I attended Public School No. 10 and Shortridge High School; I also attended Rose Polytechnic Institute in Terre Haute, Indiana. After the first year, I went to Cornell University in Ithaca, New York, where I was graduated in electrical engineering.` },
    { text: `I enlisted in the Army on October 15, 1917, at Fort Benjamin Harrison; then I went to Camp Taylor, Kentucky, where I received my first heavy jolt of liquor. My company "stole" a barrel of whiskey. The boys were rolling the barrel around the company street. I happened to be coming home from the Y.M.C.A., where I had been reading a perfectly good book. The fellows gathered around me and wanted to know if I would like to have a drink. At first I told them no, but they got a bit more persuasive and said, "Come on and have a drink." So, like an imbecile, I said, "All right, I'll show you," and took down about eight ounces. Well, boys, I didn't show them much of anything. I believe I showed myself plenty, however, and I learned right then the definite lesson that I can't drink and act like a gentleman. I was taken to the company street and rolled in the mud and they let it go at that.` },
    { pageNum: "181" },
    { text: `After my company commander saw me, I lost my sergeancy, my chances for a commission, and was confined to camp for two months. That was my first experience.` },
    { text: `After three or four months had passed, I was sent to Camp Zachary Taylor at Louisville. One night several of the boys and I decided we would go down and see Louisville, so away we went. I started drinking again and learned that if I drank three or four drinks-what we called then "a skinful"—I would have to keep going. I would have two or three days of blackout; and finally, after two or three days, I would come to and wonder what it was all about.` },
    { text: `After I was discharged from service, I went back to New York City and worked for a large electrical concern on Wall Street for several years. I was sent to Newark as a manager of a branch office. Several times I got drunk; finally I had fights with the boss and quit. I went with another company and would repeat the same procedure over again; and after seven years I found myself on the beach. I was broke.` },
    { text: `My father wanted me to come back to Indianapolis; he had heard I was drinking a bit, so I came back home at the age of 28. I had a nice automobile when I left here, but my father paid my bills and my fine in New York. I got pretty low in the subsequent years. I went in a hospital, but that didn't seem to help me. I went to a farm and that didn't help either. I got jobs; I would stay sober for a few months and then break over and start drinking.` },
    { text: `In 1930 I came in contact with Dr. Bob, and he got me in a hospital here in Indianapolis. They told me` },
    { pageNum: "182" },
    { text: `there was something that would cure me, and I grasped at anything; I think I was ready to go to the river, as several times I had put a gun to my head and each time something seemed to say to me, "You haven't got the nerve," and I didn't. I wanted to end it all. I wanted to die. I wanted to be at peace, but I didn't have what it took.` },
    { text: `After being in the hospital several days, Dr. Bob and Bill came to see me. I will never forget that day as long as I live. They told me that if I did certain things, and followed certain procedures, and took certain steps, I would be able to stop drinking. I learned that I had to take these steps and live them day by day.` },
    { text: `I then turned myself over, as I understood it, to God. I admitted I was powerless. I took a moral inventory, then tried to make restitution to the people that I had harmed over the past years. I have never known a person who honestly took these steps and followed them who did not get results.` },
    { text: `I went down on my knees and admitted that I was licked—that I was whipped. I have not had a drink from that day to this.` },
    { text: `I took that fellow's inventory—the fellow who looked at me from the mirror—and I didn't like what I saw. So, with Dr. Bob's help and Bill's help and God's help, I took those steps, and it has been my privilege to take that story and carry it to other alcoholics, and I have seen some wonderful things happen in the last eight and one-half years.` },
    { text: `I have seen family after family reunited. I have seen doctors here in Indianapolis call us in, saying, "Here is a man beyond hope. Here is` },
    { pageNum: "183" },
    { text: `a man who will never be cured. Do you think you can do anything for him?" It has been my privilege to see those men sober, reunited with their families, and staying sober, and it is a grand and glorious feeling. Why I am here tonight, I don't know. It may be that some man, some woman, is coming here for the first time, who has thought: Is there such a thing or such a place where I can go and find understanding?` },
    { text: `People who drink do understand the problem; people who do not drink do not understand the problem. I learned that I had an allergy for alcohol, and that I did not have too much will power. I had always prided myself on the fact that I had will power, but learned that it took other people's will power, along with their help, to do the job. And as long as I live it will be necessary for me to work with other alcoholics in order to maintain the equilibrium I now have and the peace of mind I possess.` },
    { text: `The A.A. program is a way of life. I have tried to live it day by day. I am not interested in whether or not I'll be sober when they take me to the cemetery. I am not interested in whether I'll be sober next week or next year. God willing, I'll be sober today, and it's the day-to-day program that I've been following and that has worked with me.` },
    { text: `I believe that that which has been given me is to be passed on to my fellow men, and as I see life today, it is one of trying to help others, trying to show others the way that I have found. I don't shove it down their throats, but I let them know there is a way and that they can find peace of mind, serenity, and happiness. They can have the respect of their families and the respect of` },
    { pageNum: "184" },
    { text: `their friends if they will only follow it. It is a grand and glorious feeling, believe me.` }
  ]
};