export const appendicesContent = {
  paragraphs: [
    { text: "THE TWELVE TRADITIONS", highlight: "basic-text" },
    { text: "1. Our common welfare should come first; personal recovery depends upon A.A. unity.", highlight: "yellow" },
    { text: "2. For our group purpose there is but one ultimate authority—a loving God as He may express Himself in our group conscience. Our leaders are but trusted servants; they do not govern.", highlight: "yellow" },
    { text: "3. The only requirement for A.A. membership is a desire to stop drinking.", highlight: "yellow" },
    { text: "4. Each group should be autonomous except in matters affecting other groups or A.A. as a whole.", highlight: "yellow" },
    { text: "5. Each group has but one primary purpose—to carry its message to the alcoholic who still suffers.", highlight: "yellow" },
    { text: "6. An A.A. group ought never endorse, finance, or lend the A.A. name to any related facility or outside enterprise, lest problems of money, property, and prestige divert us from our primary purpose.", highlight: "yellow" },
    { text: "7. Every A.A. group ought to be fully self-supporting, declining outside contributions.", highlight: "yellow" },
    { text: "8. Alcoholics Anonymous should remain forever nonprofessional, but our service centers may employ special workers.", highlight: "yellow" },
    { text: "9. A.A., as such, ought never be organized; but we may create service boards or committees directly responsible to those they serve.", highlight: "yellow" },
    { text: "10. Alcoholics Anonymous has no opinion on outside issues; hence the A.A. name ought never be drawn into public controversy.", highlight: "yellow" },
    { text: "11. Our public relations policy is based on attraction rather than promotion; we need always maintain personal anonymity at the level of press, radio, and films.", highlight: "yellow" },
    { text: "12. Anonymity is the spiritual foundation of all our Traditions, ever reminding us to place principles before personalities.", highlight: "yellow" },
    { text: "SPIRITUAL EXPERIENCE", highlight: "basic-text" },
    { text: "The terms \"spiritual experience\" and \"spiritual awakening\" are used many times in this book which, upon careful reading, shows that the personality change sufficient to bring about recovery from alcoholism has manifested itself among us in many different forms.", highlight: "yellow" },
    { text: "Most of our experiences are what the psychologist William James calls the \"educational variety\" because they develop slowly over a period of time. Quite often friends of the newcomer are aware of the difference long before he is himself. He finally realizes that he has undergone a profound alteration in his reaction to life; that such a change could hardly have been brought about by himself alone.", highlight: "blue" },
    { text: "What often takes place in a few months could seldom have been accomplished by years of self-discipline. With few exceptions our members find that they have tapped an unsuspected inner resource which they presently identify with their own conception of a Power greater than themselves.", highlight: "blue" },
    { text: "Most of us think this awareness of a Power greater than ourselves is the essence of spiritual experience. Our more religious members call it \"God-consciousness.\"", highlight: "blue" },
    { text: "Most emphatically we wish to say that any alcoholic capable of honestly facing his problems in the light of our experience can recover, provided he does not close his mind to all spiritual concepts. He can only be defeated by an attitude of intolerance or belligerent denial.", highlight: "yellow" },
    { text: "We find that no one need have difficulty with the spirituality of the program. Willingness, honesty and open mindedness are the essentials of recovery. But these are indispensable.", highlight: "yellow" },
    { text: "THE MEDICAL VIEW ON A.A.", highlight: "basic-text" },
    { text: "Since the first edition of this book was published, several important medical studies of alcoholism and the A.A. program have been conducted. The conclusion of many of these is that A.A. works, and works well.", highlight: "blue" },
    { text: "From the medical point of view, A.A. may be described as a spiritual psychotherapy supported by group dynamics. The group provides a powerful healing force through identification, emotional support, and practical advice from others who have successfully overcome the same problem.", highlight: "yellow" },
    { text: "Dr. Silkworth's theory of alcoholism as an allergy combined with an obsession has stood the test of time. Modern medicine recognizes alcoholism as a disease with physical, mental, and spiritual components. The A.A. approach addresses all three.", highlight: "yellow" },
    { text: "A.A. AND THE FAMILY", highlight: "basic-text" },
    { text: "The family of the alcoholic suffers terribly. We hope this book has made clear that alcoholism is a family illness. The entire family has been affected—emotionally, sometimes physically, and certainly spiritually.", highlight: "yellow" },
    { text: "When the alcoholic member gets sober, the family often needs time to heal as well. Resentments may linger. Trust must be rebuilt. The spouse and children may have developed their own dysfunctional patterns of coping.", highlight: "yellow" },
    { text: "We have found that patience, understanding, and living the program principles in all our affairs helps the family to heal. Many families attend Al-Anon, a fellowship for families and friends of alcoholics, which uses principles similar to those in A.A.", highlight: "blue" },
    { text: "A.A. TRADITION - HOW IT DEVELOPED", highlight: "basic-text" },
    { text: "A.A. has no rules or regulations. We are not organized in the formal sense. Yet we have found that certain principles, when followed, help us to work together effectively and to grow as a fellowship.", highlight: "yellow" },
    { text: "These principles, now known as the Twelve Traditions, evolved from our experience. They are suggestions only, yet most groups have found that they need them to survive and to serve their primary purpose—carrying the message to the alcoholic who still suffers.", highlight: "yellow" },
    { text: "The Traditions protect A.A. from internal strife and outside interference. They help us remain unified in our common purpose while respecting the autonomy of each group. They keep us focused on our primary purpose and free from outside entanglements.", highlight: "yellow" },
    { text: "PROBLEMS OTHER THAN ALCOHOL", highlight: "basic-text" },
    { text: "Some of us have had difficulties with drugs, sex, money, food, or other compulsive behaviors in addition to alcohol. We have found that the Twelve Steps work on any problem where we are powerless and our lives have become unmanageable.", highlight: "yellow" },
    { text: "However, A.A.'s primary purpose is to help alcoholics recover from alcoholism. We focus on the solution to our drinking problem. When we get sober and work the steps, we often find that our other problems become more manageable or resolve themselves.", highlight: "yellow" },
    { text: "For those with other primary addictions, there are fellowships patterned after A.A.: Narcotics Anonymous, Overeaters Anonymous, Gamblers Anonymous, and many others. These fellowships use the same basic Twelve Step program adapted to their specific problem.", highlight: "blue" }
  ],
  highlights: []
};