export const howItWorksContent = {
  paragraphs: [
    { text: "Rarely have we seen a person fail who has thoroughly followed our path. Those who do not recover are people who cannot or will not completely give themselves to this simple program, usually men and women who are constitutionally incapable of being honest with themselves." },
    { text: "Our stories disclose in a general way what we used to be like, what happened, and what we are like now. If you have decided you want what we have and are willing to go to any length to get it—then you are ready to take certain steps." },
    { text: "At some of these we balked. We thought we could find an easier, softer way. But we could not. With all the earnestness at our command, we beg of you to be fearless and thorough from the very start." },
    { text: "Remember that we deal with alcohol—cunning, baffling, powerful! Without help it is too much for us. But there is One who has all power—that One is God. May you find Him now!" },
    { text: "Half measures availed us nothing. We stood at the turning point. We asked His protection and care with complete abandon." },
    { text: "Here are the steps we took, which are suggested as a program of recovery:" },
    { text: "1. We admitted we were powerless over alcohol—that our lives had become unmanageable." },
    { text: "2. Came to believe that a Power greater than ourselves could restore us to sanity." },
    { text: "3. Made a decision to turn our will and our lives over to the care of God as we understood Him." },
    { text: "4. Made a searching and fearless moral inventory of ourselves." },
    { text: "5. Admitted to God, to ourselves, and to another human being the exact nature of our wrongs." },
    { text: "6. Were entirely ready to have God remove all these defects of character." },
    { text: "7. Humbly asked Him to remove our shortcomings." },
    { text: "8. Made a list of all persons we had harmed, and became willing to make amends to them all." },
    { text: "9. Made direct amends to such people wherever possible, except when to do so would injure them or others." },
    { text: "10. Continued to take personal inventory and when we were wrong promptly admitted it." },
    { text: "11. Sought through prayer and meditation to improve our conscious contact with God as we understood Him, praying only for knowledge of His will for us and the power to carry that out." },
    { text: "12. Having had a spiritual awakening as the result of these steps, we tried to carry this message to alcoholics, and to practice these principles in all our affairs." },
    { text: "Many of us exclaimed, \"What an order! I can't go through with it.\" Do not be discouraged. No one among us has been able to maintain anything like perfect adherence to these principles. We claim spiritual progress rather than spiritual perfection." },
    { text: "Being convinced, we were at Step Three, which is that we decided to turn our will and our life over to God as we understood Him. Just what do we mean by that, and just what do we do?" },
    { text: "The first requirement is that we be convinced that any life run on self-will can hardly be a success. Most people try to live by self-propulsion. Each person is like an actor who wants to run the whole show." },
    { text: "Selfishness—self-centeredness! That, we think, is the root of our troubles. Driven by a hundred forms of fear, self-delusion, self-seeking, and self-pity, we step on the toes of our fellows and they retaliate." },
    { text: "So our troubles, we think, are basically of our own making. They arise out of ourselves, and the alcoholic is an extreme example of self-will run riot, though he usually doesn't think so. Above everything, we alcoholics must be rid of this selfishness. We must, or it kills us! God makes that possible." },
    { text: "This is the how and why of it. First of all, we had to quit playing God. It didn't work. Next, we decided that hereafter in this drama of life, God was going to be our Director. He is the Principal; we are His agents. He is the Father, and we are His children." },
    { text: "When we sincerely took such a position, all sorts of remarkable things followed. We had a new Employer. Being all powerful, He provided what we needed, if we kept close to Him and performed His work well." },
    { text: "Many of us said to our Maker, as we understood Him: \"God, I offer myself to Thee—to build with me and to do with me as Thou wilt. Relieve me of the bondage of self, that I may better do Thy will. Take away my difficulties, that victory over them may bear witness to those I would help of Thy Power, Thy Love, and Thy Way of life. May I do Thy will always!\"" },
    { text: "Next we launched out on a course of vigorous action, the first step of which is a personal housecleaning, which many of us had never attempted. Though our decision was a vital and crucial step, it could have little permanent effect unless at once followed by a strenuous effort to face, and to be rid of, the things in ourselves which had been blocking us." },
    { text: "Therefore, we started upon a personal inventory. This was Step Four. Resentment is the \"number one\" offender. It destroys more alcoholics than anything else. From it stem all forms of spiritual disease." },
    { text: "In dealing with resentments, we set them on paper. We listed people, institutions or principles with whom we were angry. We asked ourselves why we were angry. In most cases it was found that our self-esteem, our pocketbooks, our ambitions, our personal relationships (including sex) were hurt or threatened." },
    { text: "It is plain that a life which includes deep resentment leads only to futility and unhappiness. But with the alcoholic, whose hope is the maintenance and growth of a spiritual experience, this business of resentment is infinitely grave. We found that it is fatal. For when harboring such feelings we shut ourselves off from the sunlight of the Spirit." },
    { text: "We realized that the people who wronged us were perhaps spiritually sick. Though we did not like their symptoms and the way these disturbed us, they, like ourselves, were sick too. We asked God to help us show them the same tolerance, pity, and patience that we would cheerfully grant a sick friend." },
    { text: "Referring to our list again. Putting out of our minds the wrongs others had done, we resolutely looked for our own mistakes. Where had we been selfish, dishonest, self-seeking and frightened? The inventory was ours, not the other man's." },
    { text: "We reviewed our fears thoroughly. We put them on paper. Wasn't it because self-reliance failed us? Perhaps there is a better way—we think so. For we are now on a different basis; the basis of trusting and relying upon God." },
    { text: "We never apologize to anyone for depending upon our Creator. We can laugh at those who think spirituality the way of weakness. Paradoxically, it is the way of strength. The verdict of the ages is that faith means courage. All men of faith have courage." },
    { text: "Now about sex. We reviewed our own conduct over the years past. Where had we been selfish, dishonest, or inconsiderate? In this way we tried to shape a sane and sound ideal for our future sex life. Whatever our ideal turns out to be, we must be willing to grow toward it." },
    { text: "If we have been thorough about our personal inventory, we have written down a lot. We have listed and analyzed our resentments. We have begun to comprehend their futility and their fatality. We have commenced to see their terrible destructiveness. We have begun to learn tolerance, patience and good will toward all men, even our enemies, for we look on them as sick people." },
    { text: "In this book you read again and again that faith did for us what we could not do for ourselves. We hope you are convinced now that God can remove whatever self-will has blocked you off from Him. If you have already made a decision, and an inventory of your grosser handicaps, you have made a good beginning." }
  ],
  highlights: []
};