export const manWhoMasteredFearContent = {
  paragraphs: [
    { pageNum: "252" },
    { text: `Long before I had any real opportunity to give, I had to learn the equally important lesson of receiving graciously. During my first few months in Akron, I was quite sure that I never wanted to see my hometown again. Too many economic and social problems would beset me there. I would make a fresh start somewhere else. After six months of sobriety, I saw the picture in a different light: Detroit was the place I had to return to, not only because I must face the mess I had made there, but because it was there that I could be of the most service to A.A. In the spring of 1939, Bill stopped off in Akron on his way to Detroit on business. I jumped at the suggestion that I accompany him. We spent two days there together before he returned to New York. Friends invited me to stay on for as long as I cared to. I remained with them for three weeks, using part of the time in making many amends, which I had had no earlier opportunity of making. The rest of my time was devoted to A.A. spadework. I wanted "ripe" prospects, and I didn't feel that I would get very far chasing individual drunks in and out of bars. So I spent much of my time calling on the people who I felt would logically come in contact` },
    { pageNum: "253" },
    { text: `with alcoholic cases-doctors, ministers, lawyers, and the personnel men in industry. I also talked A.A. to every friend who would listen, at lunch, at dinner, on street corners. A doctor tipped me off to my first prospect. I landed him and shipped him by train to Akron, with a pint of whiskey in his pocket to keep him from wanting to get off the train in Toledo! Nothing has ever to this day equaled the thrill of that first case. Those three weeks left me completely exhausted, and I had to return to Akron for three more months of rest. While there, two or three more "cash customers" (as Dr. Bob used to call them-probably because they had so little cash) were shipped in to us from Detroit. When I finally returned to Detroit to find work and to learn to stand on my own feet, the ball was already rolling, however slowly. But it took six more months of work and disappointments before a group of three men got together in my rooming-house bedroom for their first A.A. meeting. It sounds simple, but there were obstacles and doubts to overcome. I well remember a session I had with myself soon after I returned. It ran something like this: If I go around shouting from the rooftops about my alcoholism, it might very possibly prevent me from getting a good job. But supposing that just one man died because I had, for selfish reasons, kept my mouth shut? No. I was supposed to be doing God's will, not mine. His road lay clear before me, and I'd better quit rationalizing myself into any detours. I could not expect to keep what I had gained unless I gave it away.` },
    { pageNum: "254" },
    { text: `The Depression was still on, and jobs were scarce. My health was still uncertain. So I created a job for myself selling women's hosiery and men's made-to-order shirts. This gave me the freedom to do A.A. work and to rest for periods of two or three days when I became too exhausted to carry on. There was more than one occasion when I got up in the morning with just enough money for coffee and toast and the bus fare to carry me to my first appointment. No sale-no lunch. During that first year, however, I managed to make both ends meet and to avoid ever going back to my old habit-pattern of borrowing money when I could not earn it. Here by itself was a great step forward. During the first three months, I carried on all these activities without a car, depending entirely on buses and streetcars-I, who always had to have a car at my immediate command. I, who had never made a speech in my life and who would have been frightened sick at the prospect, stood up in front of Rotary groups in different parts of the city and talked about Alcoholics Anonymous. I, carried away with the desire to serve A.A., gave what was probably one of the first radio broadcasts about A.A., living through a case of mike fright and feeling like a million dollars when it was all over. I lived through a week of the fidgets because I had agreed to address a group of alcoholic inmates in one of our state mental hospitals. There it was the same reward-exhilaration at a mission accomplished. Do I have to tell you who gained the most out of all this?`
  ]
};