
export const moreAboutAlcoholismContent = {
  paragraphs: [
    { text: "Most of us have been unwilling to admit we were real alcoholics. No person likes to think he is bodily and mentally different from his fellows. Therefore, it is not surprising that our drinking careers have been characterized by countless vain attempts to prove we could drink like other people. The idea that somehow, someday he will control and enjoy his drinking is the great obsession of every abnormal drinker." },
    { text: "We learned that we had to fully concede to our innermost selves that we were alcoholics. This is the first step in recovery. The delusion that we are like other people, or presently may be, has to be smashed." },
    { text: "We alcoholics are men and women who have lost the ability to control our drinking. We know that no real alcoholic ever recovers control. All of us felt at times that we were regaining control, but such intervals—usually brief—were inevitably followed by still less control, which led in time to pitiful and incomprehensible demoralization." },
    { text: "Despite all we can say, many who are real alcoholics are not going to believe they are in that class. By every form of self-deception and experimentation, they will try to prove themselves exceptions to the rule, therefore nonalcoholic." },
    { text: "Here are some of the methods we have tried: Drinking beer only, limiting the number of drinks, never drinking alone, never drinking in the morning, drinking only at home, never having it in the house, never drinking during business hours, drinking only at parties, switching from scotch to brandy, drinking only natural wines, taking a trip, not taking a trip, swearing off forever, taking more physical exercise, reading inspirational books—we could increase the list ad infinitum." },
    { text: "We do not like to pronounce any individual as alcoholic, but you can quickly diagnose yourself. Step over to the nearest barroom and try some controlled drinking. Try to drink and stop abruptly. Try it more than once. It will not take long for you to decide, if you are honest with yourself about it." },
    { text: "A man of thirty was doing a great deal of spree drinking. He made up his mind that until he had been successful in business and had retired, he would not touch another drop. An exceptional man, he remained bone dry for twenty-five years and retired at the age of fifty-five, after a successful and happy business career. Then he fell victim to a belief which practically every alcoholic has—that his long period of sobriety and self-discipline had qualified him to drink as other men." },
    { text: "In two months he was in a hospital, puzzled and humiliated. Every attempt failed. Though a robust man at retirement, he went to pieces quickly and was dead within four years. This case contains a powerful lesson." },
    { text: "We have seen the truth demonstrated again and again: \"Once an alcoholic, always an alcoholic.\" Commencing to drink after a period of sobriety, we are in a short time as bad as ever. If we are planning to stop drinking, there must be no reservation of any kind, nor any lurking notion that someday we will be immune to alcohol." },
    { text: "For those who are unable to drink moderately the question is how to stop altogether. We are assuming, of course, that the reader desires to stop. Whether such a person can quit upon a nonspiritual basis depends upon the extent to which he has already lost the power to choose whether he will drink or not." },
    { text: "How then shall we help our readers determine, to their own satisfaction, whether they are one of us? The experiment of quitting for a period of time will be helpful, but we think we can render an even greater service. So we shall describe some of the mental states that precede a relapse into drinking, for obviously this is the crux of the problem." },
    { text: "What sort of thinking dominates an alcoholic who repeats time after time the desperate experiment of the first drink? Our first example is a friend we shall call Jim. He knew he was an alcoholic and in a serious condition. He knew he faced another trip to the asylum if he kept on. Moreover, he would lose his family for whom he had a deep affection. Yet he got drunk again." },
    { text: "\"I came to work on Tuesday morning. I had a few words with the boss, but nothing serious. Then I decided to drive into the country and see one of my prospects for a car. On the way I felt hungry so I stopped at a roadside place where they have a bar. I had no intention of drinking. I just thought I would get a sandwich.\"" },
    { text: "\"I sat down at a table and ordered a sandwich and a glass of milk. Still no thought of drinking. I ordered another sandwich and decided to have another glass of milk. Suddenly the thought crossed my mind that if I were to put an ounce of whiskey in my milk it couldn't hurt me on a full stomach. I ordered a whiskey and poured it into the milk.\"" },
    { text: "Here was the threat of commitment, the loss of family and position, to say nothing of that intense mental and physical suffering which drinking always caused him. Yet all reasons for not drinking were easily pushed aside in favor of the foolish idea that he could take whiskey if only he mixed it with milk! Whatever the precise definition of the word may be, we call this plain insanity." },
    { text: "You may think this an extreme case. To us it is not far-fetched, for this kind of thinking has been characteristic of every single one of us. We have sometimes reflected more than Jim did upon the consequences. But there was always the curious mental phenomenon that parallel with our sound reasoning there inevitably ran some insanely trivial excuse for taking the first drink." },
    { text: "Our behavior is as absurd and incomprehensible with respect to the first drink as that of an individual with a passion, say, for jay-walking. Through the years this conduct continues, accompanied by his continual promises to be careful. Finally, he can no longer work, his wife gets a divorce and he is held up to ridicule. Such a man would be crazy, wouldn't he?" },
    { text: "But is it? We, who have been through the wringer, have to admit if we substituted alcoholism for jay-walking, the illustration would fit us exactly. However intelligent we may have been in other respects, where alcohol has been involved, we have been strangely insane. It's strong language—but isn't it true?" },
    { text: "The actual or potential alcoholic, with hardly an exception, will be absolutely unable to stop drinking on the basis of self-knowledge. This is a point we wish to emphasize and re-emphasize, to smash home upon our alcoholic readers as it has been revealed to us out of bitter experience." },
    { text: "Fred is partner in a well known accounting firm. He has so attractive a personality that he makes friends with everyone. Yet, he is alcoholic. He had always believed in a Power greater than himself. Yet he got drunk again." },
    { text: "Let him tell you about it: \"I was much impressed with what you fellows said about alcoholism, and I frankly did not believe it would be possible for me to drink again. I reasoned I was not so far advanced as most of you fellows, that I had been usually successful in licking my other personal problems, and that I would therefore be successful where you men failed.\"" },
    { text: "\"One day I went to Washington to present some accounting evidence to a government bureau. Physically, I felt fine. My business came off well. As I crossed the threshold of the dining room, the thought came to mind that it would be nice to have a couple of cocktails with dinner. That was all. Nothing more. I ordered a cocktail and my meal. Then I ordered another cocktail.\"" },
    { text: "\"Next morning I telephoned a friend in Montreal. I now remembered what my alcoholic friends had told me, how they prophesied that if I had an alcoholic mind, the time and place would come—I would drink again. They had said that though I did raise a defense, it would one day give way before some trivial reason for having a drink. Well, just that did happen.\"" },
    { text: "\"I saw that will power and self-knowledge would not help in those strange mental blank spots. I knew from that moment that I had an alcoholic mind. I saw that will power and self-knowledge would not help in those strange mental blank spots. Finally I knew I must turn in all things to the Father of Light who presides over us all.\"" },
    { text: "A doctor said to us: \"What you say about the general hopelessness of the average alcoholic's plight is, in my opinion, correct. As to two of you men, whose stories I have heard, there is no doubt in my mind that you were 100% hopeless, apart from divine help.\"" },
    { text: "Once more: The alcoholic at certain times has no effective mental defense against the first drink. Except in a few rare cases, neither he nor any other human being can provide such a defense. His defense must come from a Higher Power." }
  ],
  highlights: []
};
