export const thereIsSolutionContent = {
  highlights: [],
  tabs: [],
  paragraphs: [
    { text: "We, of ALCOHOLICS ANONYMOUS, know thousands of men and women who were once just as hopeless as Bill. Nearly all have recovered. They have solved the drink problem." },
    { text: "We are average Americans. All sections of this country and many of its occupations are represented. We are people who normally would not mix. But there exists among us a fellowship, a friendliness, and an understanding which is indescribably wonderful." },
    { text: "The tremendous fact for every one of us is that we have discovered a common solution. We have a way out on which we can absolutely agree, and upon which we can join in brotherly and harmonious action. This is the great news this book carries to those who suffer from alcoholism." },
    { text: "An illness of this sort—and we have come to believe it an illness—involves those about us in a way no other human sickness can. If a person has cancer all are sorry for him and no one is angry or hurt. But not so with the alcoholic illness, for with it there goes annihilation of all the things worth while in life." },
    { text: "The ex-problem drinker who has found this solution, who is properly armed with facts about himself, can generally win the entire confidence of another alcoholic in a few hours. Until such an understanding is reached, little or nothing can be accomplished." },
    { text: "We had to ask ourselves why we shouldn't apply to our human problems this same readiness to change our point of view. We were having trouble with personal relationships, we couldn't control our emotional natures, we were a prey to misery and depression, we couldn't make a living, we had a feeling of uselessness, we were full of fear, we were unhappy, we couldn't seem to be of real help to other people—was not a basic solution of these bedevilments more important than whether we should see newsreels of lunar flight? Of course it was." },
    { text: "When we saw others solve their problems by a simple reliance upon the Spirit of the Universe, we had to stop doubting the power of God. Our ideas did not work. But the God idea did." },
    { text: "Moderate drinkers have little trouble in giving up liquor entirely if they have good reason for it. They can take it or leave it alone. Then we have a certain type of hard drinker. He may have the habit badly enough to gradually impair him physically and mentally. But what about the real alcoholic?" },
    { text: "He may start off as a moderate drinker; he may or may not become a continuous hard drinker; but at some stage of his drinking career he begins to lose all control of his liquor consumption, once he starts to drink." },
    { text: "Why does he behave like this? If hundreds of experiences have shown him that one drink means another debacle with all its attendant suffering and humiliation, why is it he takes that one drink? Why can't he stay on the water wagon?" },
    { text: "We know that while the alcoholic keeps away from drink, as he may do for months or years, he reacts much like other men. We are equally positive that once he takes any alcohol whatever into his system, something happens, both in the bodily and mental sense, which makes it virtually impossible for him to stop." },
    { text: "These observations would be academic and pointless if our friend never took the first drink, thereby setting the terrible cycle in motion. Therefore, the main problem of the alcoholic centers in his mind, rather than in his body." },
    { text: "The fact is that most alcoholics, for reasons yet obscure, have lost the power of choice in drink. Our so-called will power becomes practically nonexistent. We are unable, at certain times, to bring into our consciousness with sufficient force the memory of the suffering and humiliation of even a week or a month ago. We are without defense against the first drink." },
    { text: "The alcoholic may say to himself in the most casual way, \"It won't burn me this time, so here's how!\" Or perhaps he doesn't think at all. When this sort of thinking is fully established in an individual with alcoholic tendencies, he has probably placed himself beyond human aid, and unless locked up, may die or go permanently insane." },
    { text: "There is a solution. Almost none of us liked the self-searching, the leveling of our pride, the confession of shortcomings which the process requires for its successful consummation. But we saw that it really worked in others, and we had come to believe in the hopelessness and futility of life as we had been living it." },
    { text: "The great fact is just this, and nothing less: That we have had deep and effective spiritual experiences which have revolutionized our whole attitude toward life, toward our fellows and toward God's universe. The central fact of our lives today is the absolute certainty that our Creator has entered into our hearts and lives in a way which is indeed miraculous." },
    { text: "If you are as seriously alcoholic as we were, we believe there is no middle-of-the-road solution. We were in a position where life was becoming impossible, and if we had passed into the region from which there is no return through human aid, we had but two alternatives: One was to go on to the bitter end, blotting out the consciousness of our intolerable situation as best we could; and the other, to accept spiritual help." },
    { text: "A certain American business man had ability, good sense, and high character. He had consulted the best known American psychiatrists. Then he had gone to Europe, placing himself in the care of a celebrated physician (the psychiatrist, Dr. Jung) who prescribed for him. Nevertheless, he was drunk in a short time." },
    { text: "The doctor said: \"You have the mind of a chronic alcoholic. I have never seen one single case recover, where that state of mind existed to the extent that it does in you.\" Our friend felt as though the gates of hell had closed on him with a clang." },
    { text: "\"Is there no exception?\" \"Yes,\" replied the doctor, \"there is. Exceptions to cases such as yours have been occurring since early times. Here and there, once in a while, alcoholics have had what are called vital spiritual experiences. Ideas, emotions, and attitudes which were once the guiding forces of the lives of these men are suddenly cast to one side, and a completely new set of conceptions and motives begin to dominate them.\"" },
    { text: "Upon hearing this, our friend was somewhat relieved, for he reflected that, after all, he was a good church member. This hope, however, was destroyed by the doctor's telling him that while his religious convictions were very good, in his case they did not spell the necessary vital spiritual experience." },
    { text: "We, in our turn, sought the same escape with all the desperation of drowning men. What seemed at first a flimsy reed, has proved to be the loving and powerful hand of God. A new life has been given us or, if you prefer, \"a design for living\" that really works." },
    { text: "If what we have learned and felt and seen means anything at all, it means that all of us, whatever our race, creed, or color are the children of a living Creator with whom we may form a relationship upon simple and understandable terms as soon as we are willing and honest enough to try." }
  ]
};