import React from "react";
import ReactDOM from "react-dom";

// 1930s Dictionary of Key Terms - Complete Big Book Dictionary
const TERM_DEFINITIONS = {
  // A
  "abandon": "To give up completely; to desert; to leave without intent to return.",
  "abase": "To lower in rank, office, prestige, or esteem.",
  "abate": "To reduce in amount, degree, or intensity; to lessen.",
  "abject": "Low in condition; cast down in spirit; degraded.",
  "abnormal": "Deviating from the normal; irregular; unusual.",
  "abode": "Dwelling place; home.",
  "abolish": "To do away with; annul; destroy.",
  "abominable": "Worthy of or causing disgust; hateful.",
  "abound": "To be plentiful; to exist in large numbers.",
  "abrupt": "Sudden; unexpected; without preparation.",
  "abscond": "To depart secretly and hide oneself.",
  "absolve": "To free from guilt or blame; to pardon.",
  "abstain": "To refrain deliberately from an action or practice.",
  "abstinence": "Voluntary forbearance from indulgence (esp. food, drink, pleasure).",
  "abstract": "Considered apart from concrete existence; theoretical.",
  "absurd": "Ridiculously unreasonable; illogical.",
  "abundance": "Great supply; more than sufficient quantity.",
  "abuse": "Improper use; maltreatment; insult.",
  "abyss": "Bottomless gulf; immeasurable depth.",
  "accede": "To yield; to give consent or approval.",
  "accelerate": "To increase speed; hasten.",
  "accentuate": "To emphasize; to stress.",
  "accept": "To receive willingly; to agree to.",
  "access": "Approach; means of entry.",
  "accessory": "Something added; subordinate; aiding.",
  "accident": "An unforeseen event; chance mishap.",
  "acclaim": "To applaud; to praise enthusiastically.",
  "accommodate": "To provide with something needed; to adapt.",
  "accompany": "To go with; to attend.",
  "accomplish": "To bring to completion; achieve.",
  "accord": "Agreement; harmony.",
  "account": "Statement of facts; explanation.",
  "accumulate": "To gather or pile up; to increase.",
  "accurate": "Free from error; exact.",
  "accuse": "To charge with fault or offense.",
  "ache": "Continuous dull pain.",
  "achieve": "To bring to a successful end.",
  "acknowledge": "To admit as true; to recognize.",
  "acquaint": "To make familiar; to inform.",
  "acquire": "To gain possession; to obtain.",
  "acrid": "Sharp or bitter taste or smell.",
  "actuate": "To put into action; to motivate.",
  "acute": "Sharp; severe; intense.",
  "adamant": "Unyielding; inflexible.",
  "adapt": "To make suitable; to adjust.",
  "addict": "One given up to a habit or practice.",
  "adept": "Skilled; expert.",
  "adequate": "Sufficient; enough.",
  "adhere": "To stick fast; to remain devoted.",
  "adjacent": "Lying near; neighboring.",
  "adjoin": "To be next to; to border.",
  "adjourn": "To suspend until a later time.",
  "adjust": "To bring to proper order; to regulate.",
  "administer": "To manage; to give (medicine, etc.).",
  "admire": "To regard with wonder and approval.",
  "admit": "To allow entry; to confess.",
  "admonish": "To warn; to reprove gently.",
  "adore": "To worship; to love intensely.",
  "adorn": "To decorate; to add beauty.",
  "adult": "Fully grown; mature.",
  "advance": "To move forward; to promote.",
  "advantage": "Benefit; gain; superiority.",
  "advent": "Arrival; coming into being.",
  "adversary": "Opponent; enemy.",
  "adverse": "Opposed; unfavorable.",
  "advert": "To turn attention; to refer.",
  "advice": "Counsel; recommendation.",
  "advocate": "One who pleads another's cause.",
  "aesthetic": "Relating to beauty or artistic taste.",
  "affable": "Easy to talk to; pleasant.",
  "affect": "To influence; to produce an effect.",
  "affection": "Tender attachment; fondness.",
  "affirm": "To declare positively; to assert.",
  "afflict": "To cause pain or suffering.",
  "affluence": "Abundance of wealth or property.",
  "afford": "To be able to supply or bear.",
  "afraid": "Filled with fear; apprehensive.",
  "aftermath": "Result; consequence.",
  "agency": "Means of acting; instrumentality.",
  "agenda": "List of things to be done.",
  "aggravate": "To make worse; to intensify.",
  "aggregate": "Total; sum; collection.",
  "agile": "Quick; nimble.",
  "agitate": "To stir up; to excite.",
  "agony": "Intense pain of mind or body.",
  "agree": "To consent; to be in harmony.",
  "aid": "Help; assistance.",
  "aim": "Purpose; goal.",
  "airy": "Light; delicate; not substantial.",
  "alarm": "Sudden fear; warning.",
  "alert": "Watchful; quick to perceive.",
  "alien": "Foreign; strange; belonging to another.",
  "align": "To bring into line; to adjust.",
  "allege": "To assert without proof.",
  "alleviate": "To lessen; to relieve.",
  "alliance": "Union; connection.",
  "allocate": "To assign; to distribute.",
  "allow": "To permit; to grant.",
  "allude": "To refer indirectly.",
  "allure": "To attract; to entice.",
  "ally": "Associate; supporter.",
  "alone": "By oneself; solitary.",
  "aloof": "Distant; reserved.",
  "alter": "To change; to modify.",
  "alternate": "To take turns; to substitute.",
  "altercation": "Heated or angry dispute.",
  "alternative": "Choice between two or more things.",
  "altruism": "Unselfish concern for others.",
  "amass": "To collect; to gather together.",
  "amazement": "Great wonder; astonishment.",
  "ambiguous": "Having more than one meaning; uncertain.",
  "ambition": "Desire for achievement or distinction.",
  "ameliorate": "To make better; to improve.",
  "amenable": "Willing; responsive; open to influence.",
  "amiable": "Friendly; good-natured.",
  "amiss": "Out of order; wrong.",
  "amity": "Friendship; peaceful relations.",
  "ample": "More than enough; abundant.",
  "amplify": "To enlarge; to make greater.",
  "amuse": "To entertain; to cause laughter.",
  "anarchy": "Absence of government; disorder.",
  "anatomy": "Structure of an organism.",
  "ancestor": "One from whom a person descends.",
  "ancient": "Very old; of times long past.",
  "anecdote": "Short account of an incident.",
  "anguish": "Extreme pain or distress.",
  "animate": "To give life to; to enliven.",
  "animosity": "Strong hostility; hatred.",
  "annex": "To add; to attach.",
  "annihilate": "To destroy completely.",
  "annoy": "To irritate; to bother.",
  "annual": "Yearly; occurring once a year.",
  "anomaly": "Irregularity; deviation from the norm.",
  "anonymous": "Nameless; of unknown authorship.",
  "answer": "Response; solution.",
  "antagonist": "Opponent; adversary.",
  "anticipate": "To expect; to foresee.",
  "antiquated": "Old-fashioned; obsolete.",
  "antique": "Old object of value.",
  "antithesis": "Direct opposite.",
  "anxiety": "Uneasy feeling of fear or dread.",
  "apathy": "Lack of feeling; indifference.",
  "aphorism": "Short, wise saying.",
  "apocalypse": "Revelation; vision of destruction.",
  "apologize": "To express regret.",
  "apostate": "One who abandons faith or principles.",
  "appall": "To horrify; to shock.",
  "apparent": "Clear; obvious.",
  "appease": "To calm; to pacify.",
  "appetite": "Desire for food or pleasure.",
  "applaud": "To praise; to clap.",
  "apply": "To put to use; to request.",
  "appoint": "To assign; to designate.",
  "appraise": "To estimate value.",
  "appreciate": "To value highly; to be grateful.",
  "apprehend": "To arrest; to understand.",
  "approach": "To come near.",
  "appropriate": "Suitable; proper.",
  "approve": "To accept; to sanction.",
  "apt": "Suitable; quick to learn.",
  "arbitrary": "Based on whim; not fixed.",
  "arduous": "Difficult; requiring effort.",
  "arid": "Dry; barren.",
  "arise": "To get up; to come into being.",
  "armament": "Military equipment.",
  "arrogant": "Proud; overbearing.",
  "articulate": "Express clearly.",
  "artificial": "Made by humans; not natural.",
  "ascend": "To rise; to climb.",
  "ascertain": "To find out; to determine.",
  "aspire": "To seek ambitiously.",
  "assail": "To attack violently.",
  "assert": "To state positively.",
  "assess": "To evaluate; to estimate.",
  "asset": "Valuable thing or quality.",
  "assign": "To allocate; to designate.",
  "assimilate": "To absorb; to make similar.",
  "assist": "To help.",
  "associate": "To join with; companion.",
  "assuage": "To lessen; to relieve.",
  "assurance": "Confidence; guarantee.",
  "astonish": "To amaze; to surprise.",
  "astute": "Shrewd; perceptive.",
  "asylum": "Refuge; place of safety.",
  "atone": "To make amends.",
  "attach": "To fasten; to join.",
  "attain": "To achieve; to reach.",
  "attempt": "To try.",
  "attend": "To be present; to take care of.",
  "attention": "Notice; consideration.",
  "attest": "To bear witness; to certify.",
  "attire": "Clothing.",
  "attribute": "Quality; characteristic.",
  "audacious": "Bold; daring.",
  "augment": "To increase; to enlarge.",
  "auspicious": "Favorable; promising.",
  "authentic": "Genuine; real.",
  "authorize": "To empower; to permit.",
  "autonomy": "Independence; self-government.",
  "auxiliary": "Helping; supporting.",
  "avail": "To be of use; to benefit.",
  "avarice": "Greed for wealth.",
  "avenge": "To take revenge.",
  "average": "Typical; ordinary.",
  "avid": "Eager; enthusiastic.",
  "avoid": "To keep away from.",
  "await": "To wait for.",
  "awake": "To wake up; to become alert.",
  "award": "To give as a prize.",
  "awe": "Wonder mixed with fear.",
  "awkward": "Clumsy; lacking grace.",
  
  // Original A terms
  "aberration": "Partial alienation of mind; mental wandering; deviation from the right way or from truth.",
  "academic": "Theoretical; without practical or useful purpose or meaning.",
  "agnosticism": "The doctrine that God is unknown and unknowable; belief that Ultimate Cause and the essential nature of things are unknowable to man.",
  "allergy": "Acquired immunity through which a person reinfected by a germ reacts differently from the way he reacted to the primary infection.",
  "amends": "Reparation; compensation for a loss, damage, or injury inflicted.",
  "annals": "A kind of history arranged in order of time; a relation of events in chronological order, year by year.",
  "appreciation": "Judgement; recognition of worth; gratitude.",
  "arrogance": "An offensive display of self-importance or feeling of superiority.",
  "atheism": "The disbelief of the existence of a God, or a supreme intelligent Being.",
  "augury": "The art or practice of foretelling events by signs or omens; that which forebodes; prognostication.",
  "avocation": "The business which calls aside; the smaller affairs of life, or occasional calls which summon a person to leave his ordinary or principal business.",
  "axiom": "A self-evident truth; a universally accepted principle.",
  
  // B
  "bizarre": "Extravagant; grotesquely queer or strange.",
  "boon": "A gift; a grant; a benefaction; a benefit; a thing to be thankful for.",
  "brainstorm": "A type of rage; a violent, transient fit of insanity or mental derangement.",
  
  // C
  "cause": "That which produces an effect; the real reason or motive that urges, moves or implies the mind to act or decide.",
  "causes": "Those things which produce effects; the real reasons or motives that urge, move or imply the mind to act or decide.",
  "chronic": "Continuing a long time; inveterate or of long continuance, in distinction from acute.",
  "condition": "Stage of being; situation in relation to environment or to physical or mental soundness; a prerequisite.",
  "contrition": "Penitent; deep sorrow for sin; grief of heart for having done wrong.",
  "conviviality": "The good humor or mirth indulged in at entertainments; a convivial spirit or disposition; festal; social; jovial.",
  "cordial": "Proceeding as from the heart; hearty; sincere; not hypocritical; warm; affectionate.",
  "cunning": "Artfulness; craft; deceit; fraudulent skill or dexterity.",
  "cynic": "Having the qualities of a surly dog; snarling; professing unbelief in human rectitude; sarcastic; carping.",
  "cynical": "Having the qualities of a surly dog; snarling; professing unbelief in human rectitude; sarcastic; carping.",
  
  // D
  "decide": "To render a judgment; to cut off doubt; to settle a question.",
  "decision": "A judgment rendered; cutting off doubt; settling a question.",
  "denizen": "A stranger admitted to residence; a dweller.",
  "desire": "An emotion directed to the attainment of possession of an object from which pleasure is expected; a passion excited by the love of an object.",
  "despair": "Hopelessness; a hopeless state; a lack of hope or expectations.",
  "desperate": "Without hope; without regard to danger or safety; extremely reckless; proceeding from despair.",
  "devastated": "Laid waste; destroyed; overwhelmed.",
  "discipline": "Education; instruction; the cultivation of the mind and formation of the manners; training to act in accordance with rules.",
  "doubt": "Uncertainty of mind; suspense; unsettled state of opinion; to waver or fluctuate in opinion; to hesitate.",
  
  // E
  "earnest": "Serious in intention; sincere.",
  "earthly": "Of this world; material.",
  "ease": "Freedom from pain or difficulty.",
  "eccentric": "Odd; unconventional.",
  "eclectic": "Selecting from various sources.",
  "eclipse": "Obscuring of light; loss of prominence.",
  "economize": "To save; to reduce expense.",
  "ecstasy": "Intense joy; rapture.",
  "edify": "To instruct; to improve morally.",
  "effect": "Result; outcome.",
  "effective": "Producing desired result.",
  "efficiency": "Ability to accomplish with minimal waste.",
  "effort": "Exertion of energy.",
  "egotism": "Excessive self-importance.",
  "elaborate": "Detailed; complex.",
  "elapse": "To pass (time).",
  "elastic": "Flexible; adaptable.",
  "elated": "Joyful; exultant.",
  "elevate": "To lift up; to raise.",
  "eligible": "Qualified; suitable.",
  "eliminate": "To remove; to get rid of.",
  "elite": "The best; superior group.",
  "elocution": "Art of speaking clearly.",
  "eloquence": "Persuasive, fluent speech.",
  "elude": "To escape; to avoid.",
  "elusive": "Hard to grasp or define.",
  "embark": "To begin; to start a journey.",
  "embarrass": "To cause self-consciousness.",
  "embellish": "To decorate; to add detail.",
  "embrace": "To hug; to accept.",
  "emerge": "To come forth; to appear.",
  "eminent": "Distinguished; prominent.",
  "emissary": "Messenger; representative.",
  "emotions": "Feelings; states of mind.",
  "empathy": "Understanding another's feelings.",
  "emphasize": "To stress; to highlight.",
  "empower": "To give authority.",
  "enable": "To make possible.",
  "enchant": "To delight; to charm.",
  "encircle": "To surround.",
  "encompass": "To include; to contain.",
  "encourage": "To give support or confidence.",
  "endanger": "To put at risk.",
  "endeavor": "To attempt; to strive.",
  "endorse": "To approve; to support.",
  "endow": "To provide with talent or gift.",
  "endure": "To bear; to last.",
  "enemy": "Opponent; adversary.",
  "energetic": "Active; vigorous.",
  "enforce": "To compel obedience.",
  "engage": "To occupy; to involve.",
  "engender": "To cause; to bring about.",
  "enhance": "To improve; to increase.",
  "enjoy": "To take pleasure in.",
  "enlighten": "To give knowledge; to instruct.",
  "enlist": "To enroll; to join.",
  "enmity": "Hostility; hatred.",
  "ennui": "Boredom; weariness.",
  "enrage": "To make furious.",
  "enrich": "To make richer; to improve.",
  "enroll": "To register; to join.",
  "ensure": "To make certain.",
  "entail": "To involve; to require.",
  "entertain": "To amuse; to consider.",
  "enthrall": "To captivate; to hold spellbound.",
  "enthusiasm": "Intense interest; eagerness.",
  "enthusiast": "One whose imagination is highly excited with the love or in the pursuit of an object; a person of ardent zeal.",
  "entice": "To attract; to tempt.",
  "entire": "Whole; complete.",
  "entreat": "To plead; to beg.",
  "entrust": "To give responsibility.",
  "envious": "Jealous; covetous.",
  "envision": "To imagine; to picture.",
  "epic": "Long heroic poem; grand story.",
  "epidemic": "Widespread disease.",
  "episode": "Incident; event.",
  "equal": "Same in quantity or degree.",
  "equanimity": "Calmness; composure.",
  "equitable": "Fair; just.",
  "equip": "To furnish with necessary items.",
  "eradicate": "To destroy completely.",
  "erratic": "Inconsistent; irregular.",
  "erroneous": "Mistaken; incorrect.",
  "escape": "To break free.",
  "esoteric": "Understood by few; secret.",
  "especially": "Particularly; notably.",
  "essential": "Necessary; fundamental.",
  "establish": "To set up; to found.",
  "esteem": "Respect; regard.",
  "eternal": "Without end; everlasting.",
  "ethics": "Moral principles.",
  "euphoria": "Intense happiness.",
  "evade": "To avoid; to escape.",
  "evaluate": "To judge; to assess.",
  "evanescent": "Fleeting; vanishing.",
  "event": "Occurrence; happening.",
  "evidence": "Proof; indication.",
  "evoke": "To call forth; to summon.",
  "exact": "Precise; strictly accurate.",
  "exalt": "To glorify; to raise.",
  "examine": "To inspect; to study.",
  "example": "Model; illustration.",
  "exceed": "To go beyond; to surpass.",
  "excel": "To be superior.",
  "exception": "Something excluded; special case.",
  "excess": "More than enough.",
  "excite": "To arouse; to stir up.",
  "exclaim": "To cry out suddenly.",
  "exclude": "To shut out; to keep from.",
  "excursion": "Short trip; journey.",
  "excuse": "Justification; forgiveness.",
  "execute": "To carry out; to perform.",
  "exemplary": "Worthy of imitation.",
  "exempt": "Free from obligation.",
  "exercise": "Physical activity; practice.",
  "exhaust": "To drain; to tire out.",
  "exhibit": "To display; to show.",
  "exhort": "To urge strongly.",
  "exile": "Forced absence from home.",
  "exist": "To have being.",
  "exit": "Way out; departure.",
  "exotic": "Strange; foreign.",
  "expand": "To enlarge; to increase.",
  "expect": "To look forward to.",
  "expedite": "To hasten; to speed up.",
  "expel": "To drive out; to dismiss.",
  "expense": "Cost; expenditure.",
  "experience": "Knowledge gained through events.",
  "experiment": "Test; trial.",
  "expert": "Skilled; knowledgeable.",
  "explain": "To make clear.",
  "explicit": "Clear; definite.",
  "exploit": "To use selfishly; heroic deed.",
  "explore": "To investigate; to travel.",
  "expose": "To reveal; to uncover.",
  "express": "To state; to convey.",
  "extend": "To stretch out; to prolong.",
  "extensive": "Large; widespread.",
  "external": "Outside; outer.",
  "extinct": "No longer existing.",
  "extraordinary": "Unusual; remarkable.",
  "extravagant": "Excessive; wasteful.",
  "extreme": "Greatest; intense.",
  "exuberant": "Joyful; overflowing.",
  "exult": "To rejoice greatly.",
  "epoch": "A fixed point of time from which succeeding years are numbered; any fixed time or period; era; date.",
  
  // F
  "feeble": "Weak, physically or intellectually; wanting force, vigor, or efficiency.",
  "frothy": "Full of foam or froth; vain; light; empty; unsubstantial.",
  
  // G
  "gain": "To obtain; to secure.",
  "gallant": "Brave; noble; courteous.",
  "galvanize": "To stimulate; to excite into action.",
  "gamble": "To risk money on chance.",
  "garrulous": "Talkative; wordy.",
  "gaudy": "Showy; tastelessly bright.",
  "gauge": "Measure; standard of evaluation.",
  "gaunt": "Thin; haggard.",
  "generous": "Liberal in giving; unselfish.",
  "genius": "Extraordinary intellectual power.",
  "genuine": "Real; authentic.",
  "germane": "Relevant; fitting.",
  "gesture": "Movement expressing thought or feeling.",
  "ghastly": "Horrible; shocking.",
  "giddy": "Lighthearted; dizzy.",
  "gift": "Present; natural talent.",
  "gigantic": "Huge; immense.",
  "gist": "Main point; essence.",
  "glamorous": "Fascinating; alluring.",
  "glimpse": "Brief look.",
  "gloom": "Darkness; sadness.",
  "glorious": "Magnificent; splendid.",
  "gloss": "Shine; superficial explanation.",
  "glutton": "One who eats excessively.",
  "goal": "Aim; purpose.",
  "gobble": "To eat hastily.",
  "goodwill": "Friendly feeling; kindness.",
  "gorgeous": "Beautiful; splendid.",
  "grace": "Elegance; divine favor.",
  "gracious": "Kind; courteous.",
  "gradual": "Step by step; slow.",
  "grandiose": "Impressive; pompous.",
  "gratify": "To please; to satisfy.",
  "gratitude": "Thankfulness.",
  "grave": "Solemn; sober; serious; opposed to gay, light, or jovial; important; momentous.",
  "gravity": "Seriousness; importance.",
  "greed": "Excessive desire for wealth.",
  "grief": "Deep sorrow.",
  "grim": "Stern; harsh.",
  "grimy": "Dirty.",
  "grip": "Firm grasp.",
  "grotesque": "Odd; distorted.",
  "groundless": "Without reason.",
  "group": "Assembly; collection.",
  "growl": "Low threatening sound.",
  "grudge": "Ill will; resentment.",
  "guarantee": "Promise; assurance.",
  "guard": "To protect.",
  "guile": "Deceit; cunning.",
  "gullible": "Easily deceived.",
  "gush": "To pour out suddenly.",
  
  // H
  "habit": "Regular practice.",
  "hackneyed": "Overused; trite.",
  "haggard": "Worn; exhausted.",
  "hail": "To greet; to acclaim.",
  "halting": "Hesitant; faltering.",
  "hamper": "To hinder; to obstruct.",
  "handsome": "Attractive; generous.",
  "haphazard": "Random; without plan.",
  "harass": "To trouble persistently.",
  "harbinger": "Forerunner; omen.",
  "hardy": "Strong; robust.",
  "harm": "Injury; damage.",
  "harmony": "Agreement; concord.",
  "harrowing": "Distressing; painful.",
  "harsh": "Rough; severe.",
  "hasten": "To hurry.",
  "haughty": "Proud; arrogant.",
  "haven": "Place of safety.",
  "hazard": "Risk; danger.",
  "heal": "To restore health.",
  "heap": "Large pile.",
  "heed": "To pay attention.",
  "heinous": "Wicked; abominable.",
  "heir": "One who inherits.",
  "helpless": "Unable to act.",
  "herald": "Messenger; announcer.",
  "hesitate": "To pause; to be reluctant.",
  "hideous": "Horrible; repulsive.",
  "hierarchy": "System of ranks.",
  "hinder": "To obstruct; to delay.",
  "hint": "Suggestion; clue.",
  "hoard": "To accumulate secretly.",
  "hollow": "Empty; void.",
  "homage": "Respect; reverence.",
  "honest": "Truthful; sincere.",
  "honor": "High respect.",
  "hope": "Expectation of good.",
  "hospitable": "Friendly; welcoming.",
  "hostile": "Unfriendly; antagonistic.",
  "huge": "Very large.",
  "humble": "Modest; lowly.",
  "humiliate": "To disgrace; to shame.",
  "humor": "Amusement; mood.",
  "hunger": "Desire for food.",
  "hunt": "To search; to pursue.",
  "hurl": "To throw violently.",
  "hurt": "To injure; to cause pain.",
  "husky": "Strong; hoarse.",
  "hypocrisy": "Pretending to be virtuous.",
  "hypothesis": "Assumption; theory.",
  "hidebound": "Narrowly conservative; inflexible; obstinate.",
  "hopeless": "Destitute of hope; despairing; giving no ground of hope; desperate.",
  
  // I
  "ideal": "Perfect standard.",
  "idle": "Not active; lazy.",
  "idol": "Object of worship.",
  "ignoble": "Dishonorable; base.",
  "ignorant": "Lacking knowledge.",
  "illusion": "False impression.",
  "illustrious": "Famous; distinguished.",
  "immaculate": "Spotless; pure.",
  "imminent": "About to happen.",
  "immortal": "Undying; eternal.",
  "immune": "Protected; exempt.",
  "impact": "Forceful contact; effect.",
  "impartial": "Fair; unbiased.",
  "impassive": "Showing no emotion.",
  "impeccable": "Faultless; perfect.",
  "impede": "To obstruct; to hinder.",
  "impel": "To drive forward.",
  "impending": "Approaching; about to occur.",
  "imperative": "Commanding; necessary.",
  "imperil": "To endanger.",
  "impetuous": "Rash; impulsive.",
  "implement": "Tool; to carry out.",
  "implicit": "Implied; unquestioning.",
  "implore": "To beg earnestly.",
  "imply": "To suggest indirectly.",
  "import": "Significance; meaning.",
  "important": "Of great value.",
  "imposing": "Impressive; grand.",
  "impoverished": "Poor; deprived.",
  "impractical": "Not useful.",
  "imprecise": "Not exact.",
  "improbable": "Unlikely.",
  "impromptu": "Done without preparation.",
  "impropriety": "Improper conduct.",
  "improve": "To make better.",
  "impulse": "Sudden urge.",
  "inaccessible": "Hard to reach.",
  "inadequate": "Insufficient.",
  "inadvertent": "Unintentional.",
  "inane": "Silly; empty.",
  "inanimate": "Lifeless.",
  "inappropriate": "Not suitable.",
  "inaugurate": "To begin formally.",
  "incapable": "Unable.",
  "incense": "To enrage.",
  "incentive": "Motivation.",
  "incessant": "Continuous.",
  "incidental": "Minor; secondary.",
  "incisive": "Sharp; penetrating.",
  "inclination": "Tendency; preference.",
  "include": "To contain.",
  "incoherent": "Lacking clarity.",
  "incompatible": "Unable to exist together.",
  "incomplete": "Not finished.",
  "incongruous": "Out of place.",
  "inconvenient": "Causing trouble.",
  "incorporate": "To combine.",
  "increase": "To make greater.",
  "incredible": "Unbelievable.",
  "increment": "Increase; addition.",
  "incumbent": "Obligatory; holder of office.",
  "indebted": "Owing gratitude.",
  "indecent": "Improper.",
  "indefatigable": "Tireless.",
  "indelible": "Cannot be erased.",
  "indemnify": "To compensate for loss.",
  "independence": "Freedom; self-rule.",
  "indescribable": "Beyond description.",
  "indifferent": "Unconcerned.",
  "indigenous": "Native.",
  "indignant": "Angry at injustice.",
  "indispensable": "Absolutely necessary.",
  "indolent": "Lazy.",
  "induce": "To persuade.",
  "indulge": "To yield to desire.",
  "industrious": "Hardworking.",
  "ineffective": "Not producing result.",
  "ineffable": "Too great for words.",
  "inept": "Clumsy; incompetent.",
  "inert": "Motionless; inactive.",
  "inescapable": "Cannot be avoided.",
  "inevitable": "Certain to happen.",
  "inexact": "Not precise.",
  "inexcusable": "Not forgivable.",
  "inexhaustible": "Cannot be used up.",
  "inexplicable": "Not explainable.",
  "infamous": "Notorious; disgraceful.",
  "infantile": "Childish.",
  "infect": "To contaminate.",
  "infer": "To deduce.",
  "inferior": "Lower in quality.",
  "infinite": "Without limit.",
  "influence": "Power to affect.",
  "inform": "To tell; to notify.",
  "infraction": "Violation.",
  "infringe": "To encroach.",
  "ingenious": "Clever; inventive.",
  "inhabit": "To live in.",
  "inherit": "To receive from predecessor.",
  "inhibit": "To restrain.",
  "initial": "First.",
  "initiate": "To begin; to admit.",
  "injure": "To harm.",
  "innocent": "Free from guilt.",
  "innovate": "To introduce new ideas.",
  "inquire": "To ask.",
  "insane": "Unsound in mind or intellect; mad; deranged in mind; delirious; distracted.",
  "insecure": "Lacking confidence.",
  "insidious": "Lying in wait; watching an opportunity to ensnare or entrap; deceitful; sly; treacherous.",
  "insight": "Deep understanding.",
  "insinuate": "To suggest subtly.",
  "insipid": "Lacking flavor; dull.",
  "inspire": "To stimulate.",
  "instinct": "Natural impulse.",
  "institute": "Organization; to establish.",
  "instruct": "To teach.",
  "instrument": "Tool; means.",
  "insufficient": "Not enough.",
  "insulate": "To protect.",
  "insult": "To offend.",
  "insurance": "Protection against loss.",
  "intact": "Whole; undamaged.",
  "integral": "Essential.",
  "integrate": "To combine.",
  "integrity": "Honesty; wholeness.",
  "intellectual": "Relating to the mind.",
  "intense": "Strong; extreme.",
  "intensive": "Concentrated.",
  "intent": "Purpose.",
  "intercede": "To plead for another.",
  "interfere": "To meddle.",
  "interior": "Inside.",
  "interject": "To insert abruptly.",
  "interminable": "Endless.",
  "intermittent": "Occurring at intervals.",
  "internal": "Inside; within.",
  "international": "Between nations.",
  "interplay": "Reciprocal action; interaction.",
  "interpret": "To explain; to translate.",
  "interrogate": "To question formally.",
  "interrupt": "To break in upon.",
  "interval": "Space of time between events.",
  "intimate": "Close; personal; private.",
  "intimidate": "To frighten; to overawe.",
  "intolerant": "Unwilling to allow differences.",
  "intractable": "Not easily governed, managed, or taught; difficult to treat or cure.",
  "intrepid": "Fearless; bold.",
  "intricate": "Complex; detailed.",
  "intrigue": "Secret scheme; to arouse curiosity.",
  "introduce": "To present; to bring in.",
  "intuition": "Immediate knowledge without reasoning.",
  "inundate": "To flood; to overwhelm.",
  "invade": "To enter forcibly.",
  "invaluable": "Priceless; beyond value.",
  "invariable": "Unchanging.",
  "invent": "To create; to devise.",
  "invert": "To turn upside down.",
  "investigate": "To examine; to inquire into.",
  "invigorate": "To give strength; to energize.",
  "invite": "To request presence.",
  "invoke": "To call upon; to appeal.",
  "involve": "To include; to entangle.",
  "irascible": "Easily angered.",
  "irate": "Very angry.",
  "irksome": "Annoying; tedious.",
  "irregular": "Not consistent; uneven.",
  "irrelevant": "Not related.",
  "irresolute": "Indecisive.",
  "irrevocable": "Cannot be undone.",
  "isolate": "To set apart.",
  "isolation": "Separation from others; loneliness; the state of being placed alone.",
  "issue": "Matter in question; to send out.",
  "itinerant": "Traveling from place to place.",
  
  // J
  "jealous": "Envious; fearful of rivalry.",
  "jeer": "To mock; to scoff.",
  "jettison": "To throw overboard.",
  "jocular": "Humorous; playful.",
  "jovial": "Cheerful; good-humored.",
  "joyous": "Full of joy.",
  "jubilant": "Exultant; rejoicing.",
  "judgment": "Opinion; decision.",
  "judicious": "Wise; prudent.",
  "juxtapose": "To place side by side.",
  
  // K
  "keen": "Sharp; eager.",
  "kindle": "To ignite; to arouse.",
  "kindred": "Related; similar.",
  "kingly": "Regal; royal.",
  "kinship": "Family relationship.",
  "knowledge": "Awareness; understanding.",
  
  // L
  "labor": "Work; toil.",
  "labyrinth": "Maze; intricate passage.",
  "lack": "Deficiency; absence.",
  "lament": "To mourn; to regret.",
  "lampoon": "Satirical writing.",
  "languid": "Weak; listless.",
  "languish": "To lose strength.",
  "large": "Great in size.",
  "lascivious": "Lustful; lewd.",
  "lasting": "Enduring; permanent.",
  "latent": "Hidden; dormant.",
  "laud": "To praise.",
  "lavish": "Extravagant; abundant.",
  "lawful": "Legal; permitted.",
  "lax": "Loose; negligent.",
  "layman": "Nonprofessional.",
  "lazy": "Indolent; unwilling to work.",
  "lead": "To guide; to direct.",
  "league": "Association; alliance.",
  "lean": "Thin; lacking fat.",
  "learn": "To acquire knowledge.",
  "lease": "Contract for temporary use.",
  "leave": "To depart; to allow.",
  "legitimate": "Lawful; genuine.",
  "leisure": "Free time.",
  "lenient": "Mild; merciful.",
  "lethargic": "Sluggish; drowsy.",
  "level": "Flat; even.",
  "liberal": "Generous; broad-minded.",
  "liberate": "To set free.",
  "liberty": "Freedom.",
  "license": "Official permission.",
  "lick": "To strike with tongue; to defeat.",
  "lie": "Falsehood; to recline.",
  "lieu": "Place; stead.",
  "lifeless": "Without vitality.",
  "lighthearted": "Cheerful; carefree.",
  "likely": "Probable.",
  "limit": "Boundary; restriction.",
  "limpid": "Clear; transparent.",
  "lineage": "Ancestry.",
  "lingering": "Remaining; slow to end.",
  "link": "Connection.",
  "listless": "Lacking energy.",
  "literal": "Exact; word-for-word.",
  "literary": "Pertaining to literature.",
  "litigate": "To carry on a lawsuit.",
  "livid": "Pale; enraged.",
  "lofty": "High; exalted.",
  "logical": "Reasonable; rational.",
  "lonely": "Solitary; without companions.",
  "longing": "Strong desire.",
  "loom": "To appear indistinctly.",
  "loquacious": "Talkative.",
  "lordly": "Noble; arrogant.",
  "loss": "Deprivation; harm.",
  "lousy": "Inferior; contemptible.",
  "loyal": "Faithful.",
  "lucid": "Clear; easily understood.",
  "lucrative": "Profitable.",
  "ludicrous": "Absurd; laughable.",
  "lull": "Temporary calm.",
  "luminary": "Person of prominence.",
  "luminous": "Shining; bright.",
  "lurid": "Ghastly; sensational.",
  "lust": "Intense desire.",
  "luxuriant": "Abundant; fertile.",
  "luxury": "Great comfort; extravagance.",
  "lurking": "To lie hidden; to lie in wait; to lie concealed or unperceived.",
  
  // M
  "magnanimous": "Generous; noble in spirit.",
  "magnify": "To enlarge; to exaggerate.",
  "maintain": "To keep; to preserve.",
  "majestic": "Grand; stately.",
  "malady": "Any disorder or disease of the human body; a deep-seated or serious disease.",
  "malice": "Ill will; desire to harm.",
  "malign": "To slander; to defame.",
  "manage": "To control; to direct.",
  "manifest": "To show plainly; evident.",
  "manipulate": "To handle skillfully; to control.",
  "manner": "Way of acting; style.",
  "manual": "Done by hand.",
  "marvel": "Wonder; astonishment.",
  "masculine": "Male; manly.",
  "massive": "Large; heavy.",
  "master": "One who controls; expert.",
  "material": "Physical substance; matter.",
  "matriculate": "To enroll in school.",
  "mature": "Fully developed.",
  "meager": "Lacking; scanty.",
  "meander": "To wander aimlessly.",
  "meek": "Humble; submissive.",
  "melancholy": "Sadness; depression.",
  "mellifluous": "Smooth; sweet-sounding.",
  "melody": "Musical tune.",
  "menace": "Threat; danger.",
  "mentor": "Wise adviser.",
  "mercenary": "Working for money only.",
  "merciful": "Compassionate; forgiving.",
  "merit": "Worth; excellence.",
  "merry": "Joyful; cheerful.",
  "mess": "Disorder; confusion.",
  "metaphor": "Figure of speech.",
  "method": "Systematic mode or manner of action; suitable and convenient arrangement; regular or orderly procedure; system.",
  "meticulous": "Extremely careful.",
  "mettle": "Moral or physical constitution; constitutional temperament; disposition; character; temper; spirit; ardor.",
  "mighty": "Powerful; strong.",
  "militant": "Aggressive; combative.",
  "milieu": "Environment; surroundings.",
  "mimic": "To imitate.",
  "minimize": "To reduce.",
  "minister": "Clergyman; to serve.",
  "minor": "Lesser; underage.",
  "minute": "Very small; brief.",
  "miracle": "In theology, an event or effect contrary to the established constitution and course of things; a divine interposition.",
  "mischief": "Harm; annoyance.",
  "miser": "One who hoards wealth.",
  "misery": "Extreme suffering.",
  "misfortune": "Bad luck.",
  "mislead": "To deceive.",
  "mission": "Task; purpose.",
  "mistake": "Error.",
  "mistrust": "Lack of confidence.",
  "mitigate": "To lessen severity.",
  "mixed": "Combined; confused.",
  "moderate": "Temperate; not extreme.",
  "modest": "Humble; not boastful.",
  "modify": "To change.",
  "momentous": "Very important.",
  "monarch": "King; ruler.",
  "monotonous": "Lacking variety.",
  "monumental": "Huge; important.",
  "moral": "Relating to the practice, manners, or conduct of men, as social beings, in relation to each other, with reference to right and wrong.",
  "moralize": "To speak or write on moral subjects; to make moral reflections.",
  "morbid": "Diseased; unhealthy.",
  "morass": "A marsh; a fen; a tract of soft, wet ground.",
  "mortal": "Subject to death.",
  "mortify": "To humiliate.",
  "motive": "Reason; cause.",
  "mourn": "To grieve.",
  "muddle": "Confuse; disorder.",
  "multitude": "Great number.",
  "mundane": "Ordinary; worldly.",
  "munificent": "Very generous.",
  "murder": "Unlawful killing.",
  "murky": "Dark; gloomy.",
  "mysterious": "Difficult to understand.",
  
  // N
  "naive": "Innocent; unsophisticated.",
  "nasty": "Offensive; unpleasant.",
  "native": "Born in a place.",
  "natural": "Inborn; not artificial.",
  "nausea": "Sickness; disgust.",
  "neglect": "To disregard; to omit.",
  "negligent": "Careless.",
  "nemesis": "Retribution; opponent.",
  "neophyte": "Beginner.",
  "nervous": "Anxious; excitable.",
  "neutral": "Not taking sides.",
  "noble": "High moral qualities.",
  "nocturnal": "Active at night.",
  "nomad": "Wanderer.",
  "nonchalant": "Cool; unconcerned.",
  "notable": "Remarkable; worthy of note.",
  "notorious": "Widely known (often unfavorably).",
  "novel": "New; unusual.",
  "noxious": "Harmful; poisonous.",
  "nurture": "To nourish; to foster.",
  "nadir": "That point of the heavens directly opposite to the zenith; figuratively, any lowest point.",
  "notion": "Conception; mental apprehension; sentiment; opinion, usually crude or having slight foundation.",
  
  // O
  "obdurate": "Stubborn.",
  "obedient": "Dutiful; compliant.",
  "obese": "Very fat.",
  "obey": "To follow commands.",
  "object": "Thing; goal; to oppose.",
  "objective": "Purpose; unbiased.",
  "obligation": "Duty; responsibility.",
  "oblivion": "Forgetfulness; being forgotten.",
  "obnoxious": "Offensive; unpleasant.",
  "obscure": "Not clear; hidden.",
  "observe": "To watch; to notice.",
  "obsess": "To preoccupy excessively.",
  "obsession": "The state of a person vexed or besieged (as by an evil spirit); antecedent to possession.",
  "obsolete": "Out of date.",
  "obstinate": "Stubborn.",
  "obstruct": "To block.",
  "obtain": "To acquire.",
  "obvious": "Clear; evident.",
  "occasion": "Event; opportunity.",
  "occupy": "To take possession.",
  "occur": "To happen.",
  "odious": "Hateful; repulsive.",
  "offend": "To insult; to hurt.",
  "offer": "To present; to propose.",
  "official": "Authorized; formal.",
  "offspring": "Children; descendants.",
  "ominous": "Threatening.",
  "omit": "To leave out.",
  "omnipotent": "All-powerful.",
  "omniscient": "All-knowing.",
  "onerous": "Burdensome.",
  "opaque": "Not transparent.",
  "open": "Not closed; accessible.",
  "operate": "To work; to function.",
  "opinion": "Belief; judgment.",
  "opponent": "Adversary.",
  "oppose": "To resist.",
  "oppress": "To persecute; to weigh down.",
  "optimum": "Best; most favorable.",
  "option": "Choice.",
  "opulent": "Wealthy; luxurious.",
  "oration": "Formal speech.",
  "order": "Arrangement; command.",
  "ordinary": "Common; usual.",
  "organize": "To arrange systematically.",
  "origin": "Beginning; source.",
  "ornate": "Elaborately decorated.",
  "orthodox": "Traditional; established.",
  "outlandish": "Strange; bizarre.",
  "outrage": "Violent anger; offense.",
  "outstanding": "Excellent; prominent.",
  "overcome": "To conquer; to prevail.",
  "overjoyed": "Extremely happy.",
  "overpower": "To defeat; to overwhelm.",
  "oversee": "To supervise.",
  "overt": "Open; not hidden.",
  "overwhelm": "To overpower; to overcome.",
  "owing": "Due; indebted.",
  "own": "To possess.",
  "oxymoron": "Contradictory expression.",
  
  // P
  "pacify": "To calm; to soothe.",
  "pact": "Agreement; covenant.",
  "pain": "Physical or mental suffering.",
  "palatable": "Pleasant to taste.",
  "palliate": "To lessen without curing.",
  "palpable": "Tangible; easily perceived.",
  "paltry": "Insignificant; trivial.",
  "panic": "Sudden overwhelming fear.",
  "paradox": "Seeming contradiction.",
  "paramount": "Supreme; most important.",
  "pardon": "Forgiveness.",
  "parody": "Humorous imitation.",
  "parsimonious": "Stingy; frugal.",
  "partial": "Incomplete; biased.",
  "participant": "One who takes part.",
  "particular": "Specific; special.",
  "passion": "Strong emotion.",
  "passive": "Inactive; submissive.",
  "pathetic": "Arousing pity.",
  "patient": "Enduring; tolerant.",
  "patriotic": "Love of country.",
  "patron": "Supporter; benefactor.",
  "pattern": "Model; design.",
  "pauper": "Very poor person.",
  "peculiar": "Strange; unusual.",
  "pedantic": "Overly concerned with detail.",
  "peer": "Equal; companion.",
  "penalty": "Punishment.",
  "pensive": "Thoughtful; melancholy.",
  "perceive": "To become aware of.",
  "peril": "Danger.",
  "perish": "To die.",
  "permanent": "Lasting; enduring.",
  "perplex": "To confuse.",
  "persevere": "To persist.",
  "persistent": "Continuing firmly.",
  "personify": "To embody.",
  "persuade": "To convince.",
  "pertinent": "Relevant.",
  "perturb": "To disturb.",
  "peruse": "To read carefully.",
  "pessimism": "Expecting the worst.",
  "petition": "Formal request.",
  "petrify": "To paralyze with fear.",
  "petty": "Small-minded; trivial.",
  "phantom": "Illusion; ghost.",
  "phenomenon": "Extraordinary occurrence.",
  "philanthropy": "Love of mankind.",
  "phlegmatic": "Calm; unemotional.",
  "picturesque": "Striking; vivid.",
  "piety": "Devotion; reverence.",
  "pilfer": "To steal.",
  "pious": "Devout; religious.",
  "pitiful": "Arousing compassion.",
  "placate": "To appease.",
  "placid": "Calm; peaceful.",
  "plausible": "Seemingly reasonable.",
  "playful": "Full of fun.",
  "plead": "To beg; to argue.",
  "pledge": "Promise.",
  "plentiful": "Abundant.",
  "plight": "Difficult situation.",
  "plot": "Plan; scheme.",
  "plunder": "To rob.",
  "poignant": "Deeply moving.",
  "polarize": "To divide sharply.",
  "polite": "Courteous.",
  "pompous": "Arrogant; pretentious.",
  "popular": "Widely liked.",
  "portable": "Easily carried.",
  "portion": "Part; share.",
  "positive": "Certain; confident.",
  "possess": "To own.",
  "posterity": "Future generations.",
  "potent": "Powerful; mighty; having great authority or influence.",
  "potential": "Possible; capable.",
  "poverty": "State of being poor.",
  "practical": "Useful; realistic.",
  "pragmatic": "Practical; matter-of-fact.",
  "praise": "Expression of approval.",
  "precarious": "Unstable; risky.",
  "precaution": "Safeguard.",
  "precede": "To go before.",
  "precept": "Rule of conduct.",
  "precise": "Exact.",
  "predicament": "Difficult situation.",
  "predict": "To foretell.",
  "predominant": "Most frequent.",
  "preeminent": "Outstanding.",
  "prejudice": "Prejudgment; an opinion formed without due examination; an unreasonable predilection for or objection to a person or thing.",
  "preliminary": "Introductory.",
  "premise": "Proposition; basis.",
  "preoccupy": "To engross.",
  "preposterous": "Absurd.",
  "prescribe": "To recommend.",
  "presence": "Being in a place.",
  "presentiment": "Foreboding.",
  "preserve": "To protect.",
  "pressing": "Urgent.",
  "presume": "To suppose.",
  "pretend": "To feign.",
  "pretext": "Excuse.",
  "prevail": "To triumph.",
  "prevent": "To stop.",
  "prey": "Victim.",
  "priceless": "Beyond value.",
  "pride": "Self-respect; arrogance.",
  "primitive": "Early; simple.",
  "principal": "A chief or head; a chief party; one who takes and leads or principal part in anything.",
  "principle": "A general truth; a fundamental truth or tenet; a law from which others are derived; a right rule of conduct.",
  "priority": "Preference.",
  "privilege": "Special right.",
  "proclaim": "To announce.",
  "prodigal": "Wasteful.",
  "prodigy": "Marvel; wonder.",
  "profane": "Irreverent.",
  "profess": "To declare.",
  "proficient": "Skilled.",
  "profile": "Outline; description.",
  "profound": "Deep; intense.",
  "progress": "Advancement.",
  "prohibit": "To forbid.",
  "project": "Plan; undertaking.",
  "prolific": "Productive.",
  "prominent": "Noticeable; important.",
  "promise": "Assurance.",
  "promote": "To advance.",
  "prompt": "Quick; on time.",
  "pronounce": "To articulate.",
  "proof": "Evidence.",
  "proper": "Suitable.",
  "proportion": "Relation of parts.",
  "prosper": "To succeed.",
  "protect": "To guard.",
  "protest": "Objection.",
  "proud": "Self-satisfied.",
  "provide": "To supply.",
  "provincial": "Narrow-minded; local.",
  "provoke": "To anger.",
  "prudence": "Caution.",
  "prudent": "Wise; careful.",
  "psychic": "Of the mind.",
  "psychopath": "One who is morally irresponsible (used broadly in the 1930s).",
  "psychopaths": "Those who are morally irresponsible (used broadly in the 1930s).",
  "public": "Open; common.",
  "puerile": "Childish.",
  "pugnacious": "Combative.",
  "pulpit": "Platform for preaching.",
  "punctual": "On time.",
  "punish": "To penalize.",
  "puny": "Small; weak.",
  "purchase": "To buy.",
  "pure": "Clean; innocent.",
  "purge": "To cleanse.",
  "purpose": "Aim; intention.",
  "pursue": "To follow.",
  "putrid": "Rotten.",
  
  // Q
  "quaint": "Old-fashioned charm.",
  "qualify": "To meet requirements.",
  "quality": "Characteristic.",
  "quandary": "Dilemma.",
  "quantity": "Amount.",
  "quarrel": "Dispute.",
  "quash": "To suppress.",
  "quell": "To subdue.",
  "querulous": "Complaining.",
  "quest": "Search.",
  "question": "Inquiry.",
  "quibble": "Minor objection.",
  "quick": "Fast.",
  "quiet": "Calm.",
  "quixotic": "Unrealistic; idealistic.",
  "quizzical": "Puzzled.",
  "quote": "To repeat words.",
  
  // R
  "racial": "Relating to race.",
  "radical": "Extreme.",
  "rage": "Violent anger.",
  "rancor": "Bitter resentment.",
  "rank": "Position.",
  "ransack": "To plunder.",
  "rapture": "Ecstasy.",
  "rare": "Uncommon.",
  "rational": "Reasonable.",
  "ravage": "To destroy.",
  "rave": "To praise highly.",
  "reaction": "Response.",
  "readily": "Easily.",
  "realistic": "Practical.",
  "realm": "Kingdom; domain.",
  "reap": "To harvest.",
  "rear": "To raise.",
  "reason": "Cause; explanation.",
  "reassure": "To restore confidence.",
  "rebel": "One who resists authority.",
  "rebuff": "To reject.",
  "rebuild": "To construct again.",
  "recall": "To remember.",
  "recant": "To withdraw statement.",
  "recapitulate": "To summarize.",
  "receive": "To accept.",
  "recent": "Newly happened.",
  "receptive": "Open; responsive.",
  "reciprocal": "Mutual.",
  "reckless": "Careless.",
  "reclaim": "To recover.",
  "recognize": "To identify.",
  "recoil": "To shrink back.",
  "recommend": "To advise.",
  "recompense": "An equivalent returned for anything given, done or suffered; compensation; reward; amends.",
  "reconcile": "To restore harmony.",
  "record": "Written account.",
  "recourse": "Resort for help.",
  "recover": "To regain health after sickness; to grow well again; to regain a former state or condition.",
  "recovered": "Regained health after sickness; grew well again; regained a former state or condition.",
  "rectify": "To correct.",
  "recruit": "The supply of anything wasted; a reinforcement; a newly-enlisted soldier or sailor.",
  "redress": "Remedy.",
  "reduce": "To lessen.",
  "refine": "To purify.",
  "reflect": "To think; to mirror.",
  "reform": "To improve.",
  "refute": "To disprove.",
  "regal": "Royal.",
  "regret": "Sorrow.",
  "regular": "Normal.",
  "rehearse": "To practice.",
  "reign": "Rule.",
  "reinforce": "To strengthen.",
  "reject": "To refuse.",
  "rejoice": "To be glad.",
  "relapse": "Return to former state.",
  "relate": "To tell; to connect.",
  "relax": "To rest.",
  "release": "To set free.",
  "relentless": "Unyielding.",
  "relevant": "Pertinent.",
  "reliable": "Dependable.",
  "relinquish": "To give up.",
  "relish": "To enjoy.",
  "rely": "To depend.",
  "remain": "To stay.",
  "remark": "Comment.",
  "remedy": "Cure.",
  "remember": "To recall.",
  "remiss": "Negligent.",
  "remit": "To cancel; to send.",
  "remote": "Far away.",
  "remorse": "The keen pain or anguish excited by a sense of guilt; compunction of conscience for an evil act committed.",
  "remove": "To take away.",
  "render": "To provide.",
  "renew": "To make new.",
  "renounce": "To give up.",
  "repair": "To fix.",
  "repeal": "To revoke.",
  "repeat": "To say again.",
  "repel": "To drive back.",
  "replace": "To substitute.",
  "replenish": "To refill.",
  "reply": "To answer.",
  "report": "Account; description.",
  "repose": "Rest.",
  "represent": "To stand for.",
  "repress": "To restrain.",
  "reprimand": "To scold.",
  "reproach": "Censure mingled with contempt or derision; abusive reflections; shame; infamy; disgrace.",
  "reprove": "To blame; to censure; to condemn; to charge with a fault; to chide; to reprehend.",
  "repudiate": "To reject.",
  "reputation": "Public opinion.",
  "request": "Ask.",
  "require": "To need.",
  "rescue": "To save.",
  "resemble": "To look like.",
  "resent": "To feel indignation at.",
  "reserve": "To keep back; to retain.",
  "residence": "Place where one lives.",
  "resign": "To give up; to submit.",
  "resist": "To oppose; to withstand.",
  "resolution": "Firm determination.",
  "resolve": "To decide firmly.",
  "resonant": "Echoing; resounding.",
  "resource": "Supply; means of support.",
  "respect": "High regard.",
  "respire": "To breathe.",
  "restitution": "Compensation for loss.",
  "restless": "Uneasy; constantly moving.",
  "restore": "To bring back.",
  "restrain": "To hold back.",
  "result": "Outcome.",
  "resume": "To begin again.",
  "resurrect": "To bring back to life.",
  "retain": "To keep.",
  "retaliate": "To return like for like.",
  "retard": "To slow down.",
  "reticent": "Reserved; silent.",
  "retire": "To withdraw.",
  "retreat": "Withdrawal; refuge.",
  "retrieve": "To recover.",
  "return": "To come back.",
  "reveal": "To disclose.",
  "revenge": "Retaliation.",
  "revenue": "Income.",
  "reverence": "Deep respect.",
  "reverse": "Opposite; to turn back.",
  "review": "To examine again.",
  "revise": "To alter; to improve.",
  "revive": "To bring back to life.",
  "revolt": "Rebellion.",
  "reward": "Recompense.",
  "rhetoric": "Art of persuasive speaking.",
  "rhyme": "Correspondence of sounds.",
  "rhythm": "Regular beat.",
  "ridicule": "Mockery.",
  "rigid": "Stiff; inflexible.",
  "rigorous": "Severe; strict.",
  "riot": "Violent disturbance.",
  "rise": "To ascend.",
  "risk": "Chance of loss.",
  "rival": "Competitor.",
  "roam": "To wander.",
  "robust": "Strong; healthy.",
  "romantic": "Idealistic; fanciful.",
  "rotate": "To turn around.",
  "rough": "Coarse; harsh.",
  "roundabout": "Indirect.",
  "routine": "Regular procedure.",
  "rowdy": "Disorderly.",
  "royal": "Regal.",
  "rude": "Impolite.",
  "rugged": "Rough; strong.",
  "ruin": "Destruction.",
  "rule": "Regulation.",
  "ruminate": "To ponder.",
  "rural": "Countryside.",
  "rush": "To hurry.",
  "ruthless": "Cruel; merciless.",
  
  // S
  "sacred": "Holy.",
  "sacrifice": "Offering; giving up.",
  "sad": "Unhappy.",
  "safe": "Secure.",
  "sagacious": "Wise.",
  "saintly": "Virtuous.",
  "salient": "Noticeable.",
  "sallow": "Yellowish complexion.",
  "sanctify": "To make holy.",
  "sanction": "Approval; penalty.",
  "sanguine": "Confident; optimistic.",
  "sarcasm": "Cutting remark.",
  "sardonic": "Mocking; cynical.",
  "satisfy": "To fulfill.",
  "savage": "Fierce; uncivilized.",
  "save": "To rescue.",
  "scandal": "Disgraceful event.",
  "scarce": "Rare.",
  "scatter": "To disperse.",
  "scent": "Odor.",
  "scheme": "Plan.",
  "scholar": "Learned person.",
  "science": "Systematic knowledge.",
  "scorn": "Contempt.",
  "scrupulous": "Conscientious.",
  "sculpt": "To carve.",
  "seclude": "To isolate.",
  "secure": "Safe.",
  "sedate": "Calm.",
  "seduce": "To lead astray.",
  "seek": "To search.",
  "seemly": "Proper.",
  "seize": "To grasp.",
  "select": "To choose.",
  "selfish": "Concerned only with oneself.",
  "sensible": "Reasonable.",
  "sensitive": "Easily affected.",
  "sentence": "Judgment; punishment.",
  "sentiment": "Feeling.",
  "separate": "To divide.",
  "serene": "Calm.",
  "serious": "Grave.",
  "servile": "Submissive.",
  "severe": "Harsh.",
  "shabby": "Worn; inferior.",
  "shallow": "Superficial.",
  "shame": "Disgrace.",
  "shape": "Form.",
  "share": "Portion.",
  "sharp": "Keen.",
  "shatter": "To break.",
  "shelter": "Protection.",
  "shrewd": "Clever.",
  "shrill": "High-pitched.",
  "shrink": "To contract.",
  "shun": "To avoid.",
  "shy": "Timid.",
  "sibling": "Brother or sister.",
  "significant": "Important.",
  "silence": "Absence of sound.",
  "sincere": "Genuine.",
  "sinister": "Evil.",
  "skeptical": "Doubting.",
  "skill": "Ability.",
  "skirmish": "Minor battle.",
  "slothful": "Lazy.",
  "sluggish": "Slow.",
  "sly": "Cunning.",
  "small": "Little.",
  "smite": "To strike.",
  "smooth": "Even; polished.",
  "snare": "Trap.",
  "sobriety": "Temperance; moderation.",
  "sociable": "Friendly.",
  "solemn": "Serious.",
  "solid": "Firm.",
  "solitary": "Alone.",
  "solution": "Answer.",
  "somber": "Gloomy.",
  "soothe": "To calm.",
  "sophisticated": "Worldly; complex.",
  "sorrow": "Sadness.",
  "sound": "Healthy; noise.",
  "source": "Origin.",
  "spacious": "Roomy.",
  "spare": "Extra; to refrain.",
  "spark": "Flash of light.",
  "special": "Particular.",
  "specimen": "Example.",
  "spectacle": "Display.",
  "speech": "Oral expression.",
  "speed": "Rapidity.",
  "spellbound": "Fascinated.",
  "spend": "To use up.",
  "spirit": "Soul; enthusiasm.",
  "spiritual": "Sacred; relating to spirit.",
  "splendid": "Magnificent.",
  "spontaneous": "Unplanned.",
  "sporadic": "Occasional.",
  "spotless": "Clean.",
  "spurious": "False.",
  "stable": "Steady.",
  "stagnant": "Motionless.",
  "stalwart": "Strong; loyal.",
  "standard": "Norm.",
  "startle": "To surprise.",
  "stately": "Majestic.",
  "steadfast": "Firm.",
  "stealthy": "Secretive.",
  "stern": "Strict.",
  "stifle": "To suppress.",
  "stigma": "Mark of disgrace.",
  "stimulate": "To excite.",
  "stingy": "Miserly.",
  "stint": "Limitation.",
  "stoic": "Indifferent to pain.",
  "stout": "Strong; fat.",
  "straightforward": "Honest.",
  "strange": "Unusual.",
  "strategy": "Plan.",
  "strenuous": "Vigorous.",
  "strife": "Conflict.",
  "stronghold": "Fortress.",
  "struggle": "Effort; fight.",
  "stubborn": "Obstinate.",
  "stun": "To shock.",
  "sturdy": "Robust.",
  "subdue": "To conquer.",
  "sublime": "Exalted.",
  "submissive": "Yielding.",
  "subordinate": "Lower in rank.",
  "subsequent": "Following.",
  "substantial": "Considerable.",
  "subtle": "Delicate.",
  "subvert": "To overthrow.",
  "succeed": "To prosper.",
  "succumb": "To yield.",
  "suffer": "To endure pain.",
  "suffice": "To be enough.",
  "suggest": "To propose.",
  "suitable": "Appropriate.",
  "sulky": "Morose.",
  "sumptuous": "Lavish.",
  "superficial": "Shallow.",
  "superfluous": "Excessive.",
  "superior": "Higher in quality.",
  "supple": "Flexible.",
  "suppress": "To restrain.",
  "surmise": "To guess.",
  "surpass": "To exceed.",
  "surplus": "Excess.",
  "surprise": "Unexpected event.",
  "surrender": "To give up.",
  "survive": "To remain alive.",
  "susceptible": "Easily influenced.",
  "suspicion": "Doubt.",
  "sustain": "To support.",
  "swindle": "To cheat.",
  "sympathetic": "Compassionate.",
  "symbol": "Sign.",
  "symmetry": "Balanced proportions.",
  "sympathy": "Sharing of feelings.",
  "systematic": "Methodical.",
  
  // T
  "tact": "Sensitivity in dealing with others.",
  "taint": "Contamination.",
  "tame": "Domesticated.",
  "tangible": "Perceptible by touch.",
  "tantalize": "To tease.",
  "tardy": "Late.",
  "tarnish": "To dull.",
  "tarry": "To linger.",
  "taut": "Tight.",
  "teach": "To instruct.",
  "teem": "To abound.",
  "temper": "Moderation; mood.",
  "temperance": "Moderation; self-restraint.",
  "tempest": "Violent storm.",
  "tempt": "To entice.",
  "tenacious": "Persistent.",
  "tender": "Gentle; soft.",
  "tense": "Nervous; tight.",
  "tentative": "Uncertain.",
  "terminate": "To end.",
  "terrible": "Dreadful.",
  "terrific": "Wonderful.",
  "terror": "Extreme fear.",
  "testify": "To bear witness.",
  "testimony": "Evidence.",
  "thankful": "Grateful.",
  "thirst": "Desire for drink.",
  "thorough": "Complete.",
  "thoughtful": "Considerate.",
  "threat": "Danger.",
  "thrive": "To prosper.",
  "throng": "Crowd.",
  "thrust": "To push.",
  "thwart": "To oppose.",
  "timid": "Shy.",
  "tireless": "Indefatigable.",
  "tolerant": "Accepting.",
  "tolerate": "To endure.",
  "topple": "To overturn.",
  "torment": "Severe suffering.",
  "tornado": "Violent windstorm.",
  "torture": "Extreme pain.",
  "total": "Entire.",
  "touch": "To feel.",
  "tough": "Strong; difficult.",
  "tragic": "Disastrous.",
  "tranquil": "Peaceful.",
  "transcend": "To rise above.",
  "transient": "Temporary.",
  "transparent": "Clear.",
  "treacherous": "Disloyal; dangerous.",
  "treasure": "Valuable possession.",
  "tremendous": "Very great.",
  "tranquility": "Peace; calm.",
  "transfigure": "To change appearance.",
  "transform": "To change form.",
  "transgress": "To violate law or command.",
  "transition": "Change from one state to another.",
  "transitory": "Temporary.",
  "travail": "Hard work; toil.",
  "treason": "Betrayal of trust.",
  "tremor": "Shaking.",
  "trifle": "Small matter.",
  "trite": "Overused; commonplace.",
  "triumph": "Victory.",
  "trivial": "Insignificant.",
  "troublesome": "Difficult; annoying.",
  "truce": "Temporary peace.",
  "trudge": "To walk wearily.",
  "true": "Genuine; accurate.",
  "trust": "Confidence; reliance.",
  "truth": "Reality; fact.",
  "tumult": "Disorder; uproar.",
  "turbulent": "Violent; stormy.",
  "turmoil": "Confusion.",
  "tyranny": "Oppressive rule.",
  
  // U
  "ugly": "Unpleasant to look at.",
  "ultimate": "Final; fundamental.",
  "unanimous": "In complete agreement.",
  "uncanny": "Strange; mysterious.",
  "uncertain": "Not sure.",
  "uncommon": "Rare.",
  "unconscious": "Not awake.",
  "uncouth": "Crude; awkward.",
  "undermine": "To weaken.",
  "understand": "To grasp meaning.",
  "undertake": "To assume responsibility.",
  "undue": "Excessive.",
  "uneasy": "Restless; anxious.",
  "unfathomable": "Beyond understanding.",
  "unfortunate": "Unlucky.",
  "ungainly": "Clumsy.",
  "unify": "To make one.",
  "unique": "One of a kind.",
  "universal": "Applicable everywhere.",
  "unkempt": "Untidy.",
  "unknown": "Not known.",
  "unlawful": "Illegal.",
  "unlimited": "Without bounds.",
  "unruly": "Disorderly.",
  "unselfish": "Generous.",
  "untidy": "Messy.",
  "untimely": "Premature.",
  "unusual": "Extraordinary.",
  "unveil": "To reveal.",
  "unwieldy": "Hard to manage.",
  "unwise": "Foolish.",
  "upbraid": "To scold.",
  "uphold": "To support.",
  "uplift": "To raise; to inspire.",
  "upright": "Honest; vertical.",
  "urge": "Strong desire.",
  "urgent": "Needing immediate action.",
  "useful": "Helpful.",
  "usual": "Common.",
  
  // V
  "vacant": "Empty.",
  "vague": "Indefinite.",
  "vain": "Conceited; futile.",
  "valid": "Sound; legally binding.",
  "valiant": "Brave.",
  "valuable": "Worth much.",
  "vanity": "Excessive pride.",
  "vary": "To change.",
  "vast": "Immense.",
  "vehement": "Intense; passionate.",
  "venerable": "Worthy of respect.",
  "vengeance": "Revenge.",
  "venial": "Forgivable.",
  "venture": "Risky undertaking.",
  "veracity": "Truthfulness.",
  "verdict": "Judgment.",
  "verify": "To confirm.",
  "versatile": "Adaptable.",
  "version": "Form; translation.",
  "vertical": "Upright.",
  "vestige": "Trace; remnant.",
  "vex": "To annoy.",
  "vibrant": "Lively.",
  "vice": "Immoral habit.",
  "victorious": "Triumphant.",
  "vigilant": "Watchful.",
  "vigorous": "Strong; energetic.",
  "villain": "Wicked person.",
  "vindicate": "To clear from blame.",
  "violent": "Forceful; destructive.",
  "virtue": "Moral excellence.",
  "virtuous": "Righteous.",
  "vision": "Sight; foresight.",
  "vivid": "Bright; clear.",
  "vociferous": "Loud; noisy.",
  "volatile": "Unstable; explosive.",
  "volition": "Will; choice.",
  "voluble": "Talkative.",
  "volunteer": "One who offers freely.",
  "voracious": "Greedy.",
  "vow": "Solemn promise.",
  "vulnerable": "Open to harm.",
  
  // W
  "wane": "To diminish.",
  "wanton": "Reckless; immoral.",
  "wary": "Cautious.",
  "waste": "To squander.",
  "watchful": "Alert.",
  "weak": "Lacking strength.",
  "wealth": "Abundance of possessions.",
  "weary": "Tired.",
  "weird": "Strange.",
  "welcome": "Warm reception.",
  "welfare": "Well-being.",
  "whimsical": "Fanciful.",
  "whole": "Entire.",
  "wicked": "Evil.",
  "wide": "Broad.",
  "willful": "Stubborn.",
  "willing": "Ready; eager.",
  "win": "To succeed.",
  "wise": "Prudent.",
  "wish": "Desire.",
  "withdraw": "To retreat.",
  "withhold": "To keep back.",
  "witness": "One who sees.",
  "witty": "Clever.",
  "wonderful": "Marvelous.",
  "worn": "Used; tired.",
  "worthy": "Deserving.",
  "wretched": "Miserable.",
  
  // Y
  "yearn": "To long for.",
  "yield": "To give way.",
  "young": "Not old.",
  
  // Z
  "zeal": "Passion.",
  "zealous": "Enthusiastic.",
  "zenith": "Highest point.",
  "zephyr": "Gentle breeze.",
  "zest": "Enjoyment; relish.",
  "zone": "Area.",
  "zoology": "Study of animals.",
  
  // S
  "sober": "Temperate in the use of spiritous liquors; not intoxicated; not mad or insane; self-possessed; regular; calm; thoughtful.",
  "sobriety": "Habitual soberness or temperance; freedom from intoxication; habitual freedom from enthusiasm, inordinate passion, or overheated imagination; calmness.",
  "spiritual": "Consisting of spirit; not material; mental; intellectual; not gross; refined from external things; pure; holy.",
  "subtle": "Characterized by artful cunning; sly; crafty; insinuating; wily; characterized by acuteness or delicacy of intellect.",
  "succumb": "To yield to a superior force; to give up.",
  "succumbed": "Yielded to a superior force; gave up.",
  "suffice": "To be enough or sufficient; to be equal to the end proposed; to be adequate or satisfactory.",
  "synthesis": "Composition; the putting of two or more things together; combination or that process of reasoning in which we advance by regular chain from principles.",
  "synthetic": "Pertaining to synthesis; consisting in synthesis or composition.",
  
  // T
  "temperance": "Moderation; particularly, habitual moderation in regard to the indulgence of the natural appetites and passions; specifically, total abstinence from intoxicating liquors.",
  "temperate": "Moderate; not excessive; moderate in the indulgence of the appetites and passions; cool; calm; not marked with passion.",
  "temporize": "To comply with the time or occasion; to humor or yield to the current of opinion or to circumstances; to delay; to procrastinate.",
  
  // U
  "utter": "The utmost limit.",
  "utterly": "In an utter manner; to the full extent; fully; perfectly; totally.",
  
  // V
  "vicissitude": "Regular change or succession of one thing to another; a passing from one state or condition to another; irregular change; revolution; mutation.",
  "vital": "Pertaining to life; contributing to life; necessary to life; very necessary; highly important; essential.",
  
  // W
  "wholesale": "The sale of goods by the piece or large quantity; in great quantities; extensive and indiscriminate.",
  "whoopee": "To engage in noisy, boisterous celebration; to make merry with noise (archaic term for a bender/spree).",
  "wrest": "To twist; to wrench; to extort or bring out by force; to turn from truth or twist from the natural or proper meaning; to pervert; to distort.",
};

export function wrapTermsInText(text) {
  if (!text) return text;
  
  // Sort terms by length (longest first) to avoid partial matches
  const sortedTerms = Object.keys(TERM_DEFINITIONS).sort((a, b) => b.length - a.length);
  
  let result = text;
  const replacements = [];
  
  // Find all term matches first
  sortedTerms.forEach(term => {
    const regex = new RegExp(`\\b(${term})\\b`, 'gi');
    let match;
    while ((match = regex.exec(text)) !== null) {
      replacements.push({
        start: match.index,
        end: match.index + match[0].length,
        term: match[0],
        definition: TERM_DEFINITIONS[term.toLowerCase()]
      });
    }
  });
  
  // Sort by position (reverse) and replace
  replacements.sort((a, b) => b.start - a.start);
  
  replacements.forEach(rep => {
    const before = result.slice(0, rep.start);
    const after = result.slice(rep.end);
    result = before + `{{TERM:${rep.term}:${rep.definition}}}` + after;
  });
  
  return result;
}

export default function TermTooltip({ term, definition }) {
  const [showTooltip, setShowTooltip] = React.useState(false);

  const handleClick = (e) => {
    e.preventDefault();
    e.stopPropagation();
    setShowTooltip(true);
    // Prevent body scroll on mobile when modal is open
    document.body.style.overflow = 'hidden';
    document.body.style.position = 'fixed';
    document.body.style.width = '100%';
    document.body.style.top = `-${window.scrollY}px`;
  };

  const handleClose = (e) => {
    if (e) {
      e.preventDefault();
      e.stopPropagation();
    }
    // Restore body scroll and position
    const scrollY = document.body.style.top;
    document.body.style.overflow = '';
    document.body.style.position = '';
    document.body.style.width = '';
    document.body.style.top = '';
    window.scrollTo(0, parseInt(scrollY || '0') * -1);
    setShowTooltip(false);
  };

  // Clean up on unmount
  React.useEffect(() => {
    return () => {
      document.body.style.overflow = '';
      document.body.style.position = '';
      document.body.style.width = '';
      document.body.style.top = '';
    };
  }, []);

  // Use portal to render modal at document body level
  const modalContent = showTooltip ? ReactDOM.createPortal(
    <div 
      className="big-book-modal-overlay" 
      onClick={handleClose}
      role="dialog"
      aria-modal="true"
      aria-labelledby="term-title"
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 999999
      }}
    >
      <div 
        className="big-book-modal-popup" 
        onClick={(e) => e.stopPropagation()}
      >
        <div className="big-book-modal-header">
          <span id="term-title" className="big-book-modal-term">{term}</span>
          <button 
            className="big-book-modal-close" 
            onClick={handleClose}
            aria-label="Close definition"
            type="button"
          >
            ×
          </button>
        </div>
        <div className="big-book-modal-label">1930s Meaning</div>
        <div className="big-book-modal-definition">{definition}</div>
      </div>
    </div>,
    document.body
  ) : null;

  return (
    <>
      <span 
        className="big-book-term" 
        tabIndex={0}
        onClick={handleClick}
        onKeyDown={(e) => e.key === 'Enter' && handleClick(e)}
        role="button"
        aria-label={`Definition of ${term}`}
      >
        {term}
      </span>
      {modalContent}
    </>
  );
}

export function renderTextWithTerms(text) {
  if (!text) return null;
  
  const processed = wrapTermsInText(text);
  const parts = processed.split(/(\{\{TERM:[^}]+\}\})/g);
  
  return parts.map((part, idx) => {
    const match = part.match(/\{\{TERM:([^:]+):([^}]+)\}\}/);
    if (match) {
      return <TermTooltip key={idx} term={match[1]} definition={match[2]} />;
    }
    return <span key={idx}>{part}</span>;
  });
}